package com.unicast.campaign.impl;
// Generated Sep 19, 2006 10:24:53 PM by Hibernate Tools 3.1.0 beta3

import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.math.BigDecimal;
import javax.persistence.*;

import org.hibernate.CacheMode;
import com.unicast.campaign.interf.*;

// http://www.experts-exchange.com/Programming/Programming_Languages/Java/Q_21743817.html

/**
 * CampaignVw generated by hbm2java
 */

/*

 String Q_GET_ALL_AD_MGMT_INFO = 
        	"select vw.* from FUSE_RP.AD_MGMT_VW vw, fuse_ui.status_reference sr, fuse_ui.status s, fuse_ui.ads_placement p "+
        	"where 1=1 "+
        	"and vw.placement_id = p.placement_id "+
        	"and p.status_reference_id = sr.status_reference_id "+
        	"and sr.status_id = s.status_id "+
        	TOKEN_WHERE_CLAUSE +
            " order by lower(vw.campaign_name), lower(vw.publisher_name), lower(vw.placement_name) ";

*/


@Entity
@Table(name="AD_MGMT_VW"
    ,schema="FUSE_RP"
)

public class AdMgmtVw  implements IAdMgmtVw, java.io.Serializable {
      
	// Fields    

    private Integer adId;
    private Long creativeId;
    private String creativeName;
    private Integer placementId;
    private String placementName;
    private short campaignId;
    private String campaignName;
    private Date campaignStartDate;
    private Date campaignEndDate;
    private String campaignPo;
    private short publisherId;
    private String publisherName;
    private short advertiserId;
    private String advertiserName;
    private short agencyId;
    private String agencyName;
    private String billablePartyBusType;
    private String vwptSalesManager;
    private String vwptSalesLocation;
    private BigDecimal vwptCsrId;
    private String vwptCsrName;
    private Long placementCap;
    private Date placementStartDate;
    private Date placementEndDate;
    private String creativeProductGroup;
    private String creativeFormat;
    private String creativeTechnologyType;
    private BigDecimal creativeFileSize;
    private BigDecimal creativeCpm;
    private String billablePartyContactName;
    private String billablePartyAddress;
    private String billablePartyPhone;
    private String billablePartyFax;
    private String billablePartyEmail;
    private Long adPlannedImps;
    private Boolean impressionToCount;
    private BigDecimal creativeFullPlayLength;
    private String billingName;
    private short videoPlayTime;
     
    // Constructors
 	 
 	/** default constructor */
     public AdMgmtVw() {
    
     }
     
     /** full constructor */
     public AdMgmtVw(Integer adId, Long creativeId, String creativeName, Integer placementId, String placementName, short campaignId, String campaignName, Date campaignStartDate, Date campaignEndDate, String campaignPo, short publisherId, String publisherName, short advertiserId, String advertiserName, short agencyId, String agencyName, String billablePartyBusType, String vwptSalesManager, String vwptSalesLocation, BigDecimal vwptCsrId, String vwptCsrName, Long placementCap, Date placementStartDate, Date placementEndDate, String creativeProductGroup, String creativeFormat, String creativeTechnologyType, BigDecimal creativeFileSize, BigDecimal creativeCpm, String billablePartyContactName, String billablePartyAddress, String billablePartyPhone, String billablePartyFax, String billablePartyEmail, Long adPlannedImps, Boolean impressionToCount, BigDecimal creativeFullPlayLength, String billingName, short videoPlayTime) {
         
    	 this.adId = adId;
         this.creativeId = creativeId;
         this.creativeName = creativeName;
         this.placementId = placementId;
         this.placementName = placementName;
         this.campaignId = campaignId;
         this.campaignName = campaignName;
         this.campaignStartDate = campaignStartDate;
         this.campaignEndDate = campaignEndDate;
         this.campaignPo = campaignPo;
         this.publisherId = publisherId;
         this.publisherName = publisherName;
         this.advertiserId = advertiserId;
         this.advertiserName = advertiserName;
         this.agencyId = agencyId;
         this.agencyName = agencyName;
         this.billablePartyBusType = billablePartyBusType;
         this.vwptSalesManager = vwptSalesManager;
         this.vwptSalesLocation = vwptSalesLocation;
         this.vwptCsrId = vwptCsrId;
         this.vwptCsrName = vwptCsrName;
         this.placementCap = placementCap;
         this.placementStartDate = placementStartDate;
         this.placementEndDate = placementEndDate;
         this.creativeProductGroup = creativeProductGroup;
         this.creativeFormat = creativeFormat;
         this.creativeTechnologyType = creativeTechnologyType;
         this.creativeFileSize = creativeFileSize;
         this.creativeCpm = creativeCpm;
         this.billablePartyContactName = billablePartyContactName;
         this.billablePartyAddress = billablePartyAddress;
         this.billablePartyPhone = billablePartyPhone;
         this.billablePartyFax = billablePartyFax;
         this.billablePartyEmail = billablePartyEmail;
         this.adPlannedImps = adPlannedImps;
         this.impressionToCount = impressionToCount;
         this.creativeFullPlayLength = creativeFullPlayLength;
         this.billingName = billingName;
         this.videoPlayTime = videoPlayTime;
     }

 	
     public List<IAdMgmtVw> executeQuery(EntityManager entityManager, String where, String order) {
     	
    	 return null;
         
     }
     
//   Property accessors
     @Id
     @Column(name="AD_ID", unique=false, nullable=false, insertable=true, updatable=true, precision=6, scale=0)

     public Integer getAdId() {
         return this.adId;
     }
     
     public void setAdId(Integer adId) {
         this.adId = adId;
     }
     @Column(name="CREATIVE_ID", unique=false, nullable=true, insertable=true, updatable=true, precision=10, scale=0)

     public Long getCreativeId() {
         return this.creativeId;
     }
     
     public void setCreativeId(Long creativeId) {
         this.creativeId = creativeId;
     }
     @Column(name="CREATIVE_NAME", unique=false, nullable=true, insertable=true, updatable=true, length=60)

     public String getCreativeName() {
         return this.creativeName;
     }
     
     public void setCreativeName(String creativeName) {
         this.creativeName = creativeName;
     }
     @Column(name="PLACEMENT_ID", unique=false, nullable=false, insertable=true, updatable=true, precision=6, scale=0)

     public Integer getPlacementId() {
         return this.placementId;
     }
     
     public void setPlacementId(Integer placementId) {
         this.placementId = placementId;
     }
     @Column(name="PLACEMENT_NAME", unique=false, nullable=true, insertable=true, updatable=true, length=64)

     public String getPlacementName() {
         return this.placementName;
     }
     
     public void setPlacementName(String placementName) {
         this.placementName = placementName;
     }
     @Column(name="CAMPAIGN_ID", unique=false, nullable=false, insertable=true, updatable=true, precision=4, scale=0)

     public short getCampaignId() {
         return this.campaignId;
     }
     
     public void setCampaignId(short campaignId) {
         this.campaignId = campaignId;
     }
     @Column(name="CAMPAIGN_NAME", unique=false, nullable=true, insertable=true, updatable=true, length=40)

     public String getCampaignName() {
         return this.campaignName;
     }
     
     public void setCampaignName(String campaignName) {
         this.campaignName = campaignName;
     }
     @Column(name="CAMPAIGN_START_DATE", unique=false, nullable=true, insertable=true, updatable=true, length=7)

     public Date getCampaignStartDate() {
         return this.campaignStartDate;
     }
     
     public void setCampaignStartDate(Date campaignStartDate) {
         this.campaignStartDate = campaignStartDate;
     }
     @Column(name="CAMPAIGN_END_DATE", unique=false, nullable=true, insertable=true, updatable=true, length=7)

     public Date getCampaignEndDate() {
         return this.campaignEndDate;
     }
     
     public void setCampaignEndDate(Date campaignEndDate) {
         this.campaignEndDate = campaignEndDate;
     }
     @Column(name="CAMPAIGN_PO", unique=false, nullable=true, insertable=true, updatable=true, length=24)

     public String getCampaignPo() {
         return this.campaignPo;
     }
     
     public void setCampaignPo(String campaignPo) {
         this.campaignPo = campaignPo;
     }
     @Column(name="PUBLISHER_ID", unique=false, nullable=false, insertable=true, updatable=true, precision=4, scale=0)

     public short getPublisherId() {
         return this.publisherId;
     }
     
     public void setPublisherId(short publisherId) {
         this.publisherId = publisherId;
     }
     @Column(name="PUBLISHER_NAME", unique=false, nullable=true, insertable=true, updatable=true, length=60)

     public String getPublisherName() {
         return this.publisherName;
     }
     
     public void setPublisherName(String publisherName) {
         this.publisherName = publisherName;
     }
     @Column(name="ADVERTISER_ID", unique=false, nullable=false, insertable=true, updatable=true, precision=4, scale=0)

     public short getAdvertiserId() {
         return this.advertiserId;
     }
     
     public void setAdvertiserId(short advertiserId) {
         this.advertiserId = advertiserId;
     }
     @Column(name="ADVERTISER_NAME", unique=false, nullable=true, insertable=true, updatable=true, length=60)

     public String getAdvertiserName() {
         return this.advertiserName;
     }
     
     public void setAdvertiserName(String advertiserName) {
         this.advertiserName = advertiserName;
     }
     @Column(name="AGENCY_ID", unique=false, nullable=false, insertable=true, updatable=true, precision=4, scale=0)

     public short getAgencyId() {
         return this.agencyId;
     }
     
     public void setAgencyId(short agencyId) {
         this.agencyId = agencyId;
     }
     @Column(name="AGENCY_NAME", unique=false, nullable=true, insertable=true, updatable=true, length=40)

     public String getAgencyName() {
         return this.agencyName;
     }
     
     public void setAgencyName(String agencyName) {
         this.agencyName = agencyName;
     }
     @Column(name="BILLABLE_PARTY_BUS_TYPE", unique=false, nullable=true, insertable=true, updatable=true, length=20)

     public String getBillablePartyBusType() {
         return this.billablePartyBusType;
     }
     
     public void setBillablePartyBusType(String billablePartyBusType) {
         this.billablePartyBusType = billablePartyBusType;
     }
     @Column(name="VWPT_SALES_MANAGER", unique=false, nullable=true, insertable=true, updatable=true, length=61)

     public String getVwptSalesManager() {
         return this.vwptSalesManager;
     }
     
     public void setVwptSalesManager(String vwptSalesManager) {
         this.vwptSalesManager = vwptSalesManager;
     }
     @Column(name="VWPT_SALES_LOCATION", unique=false, nullable=true, insertable=true, updatable=true, length=105)

     public String getVwptSalesLocation() {
         return this.vwptSalesLocation;
     }
     
     public void setVwptSalesLocation(String vwptSalesLocation) {
         this.vwptSalesLocation = vwptSalesLocation;
     }
     @Column(name="VWPT_CSR_ID", unique=false, nullable=true, insertable=true, updatable=true, precision=22, scale=0)

     public BigDecimal getVwptCsrId() {
         return this.vwptCsrId;
     }
     
     public void setVwptCsrId(BigDecimal vwptCsrId) {
         this.vwptCsrId = vwptCsrId;
     }
     @Column(name="VWPT_CSR_NAME", unique=false, nullable=true, insertable=true, updatable=true, length=61)

     public String getVwptCsrName() {
         return this.vwptCsrName;
     }
     
     public void setVwptCsrName(String vwptCsrName) {
         this.vwptCsrName = vwptCsrName;
     }
     @Column(name="PLACEMENT_CAP", unique=false, nullable=true, insertable=true, updatable=true, precision=12, scale=0)

     public Long getPlacementCap() {
         return this.placementCap;
     }
     
     public void setPlacementCap(Long placementCap) {
         this.placementCap = placementCap;
     }
     @Column(name="PLACEMENT_START_DATE", unique=false, nullable=true, insertable=true, updatable=true, length=7)

     public Date getPlacementStartDate() {
         return this.placementStartDate;
     }
     
     public void setPlacementStartDate(Date placementStartDate) {
         this.placementStartDate = placementStartDate;
     }
     @Column(name="PLACEMENT_END_DATE", unique=false, nullable=true, insertable=true, updatable=true, length=7)

     public Date getPlacementEndDate() {
         return this.placementEndDate;
     }
     
     public void setPlacementEndDate(Date placementEndDate) {
         this.placementEndDate = placementEndDate;
     }
     @Column(name="CREATIVE_PRODUCT_GROUP", unique=false, nullable=false, insertable=true, updatable=true, length=40)

     public String getCreativeProductGroup() {
         return this.creativeProductGroup;
     }
     
     public void setCreativeProductGroup(String creativeProductGroup) {
         this.creativeProductGroup = creativeProductGroup;
     }
     @Column(name="CREATIVE_FORMAT", unique=false, nullable=false, insertable=true, updatable=true, length=40)

     public String getCreativeFormat() {
         return this.creativeFormat;
     }
     
     public void setCreativeFormat(String creativeFormat) {
         this.creativeFormat = creativeFormat;
     }
     @Column(name="CREATIVE_TECHNOLOGY_TYPE", unique=false, nullable=false, insertable=true, updatable=true, length=30)

     public String getCreativeTechnologyType() {
         return this.creativeTechnologyType;
     }
     
     public void setCreativeTechnologyType(String creativeTechnologyType) {
         this.creativeTechnologyType = creativeTechnologyType;
     }
     @Column(name="CREATIVE_FILE_SIZE", unique=false, nullable=true, insertable=true, updatable=true, precision=10)

     public BigDecimal getCreativeFileSize() {
         return this.creativeFileSize;
     }
     
     public void setCreativeFileSize(BigDecimal creativeFileSize) {
         this.creativeFileSize = creativeFileSize;
     }
     @Column(name="CREATIVE_CPM", unique=false, nullable=true, insertable=true, updatable=true, precision=22, scale=0)

     public BigDecimal getCreativeCpm() {
         return this.creativeCpm;
     }
     
     public void setCreativeCpm(BigDecimal creativeCpm) {
         this.creativeCpm = creativeCpm;
     }
     @Column(name="BILLABLE_PARTY_CONTACT_NAME", unique=false, nullable=true, insertable=true, updatable=true, length=61)

     public String getBillablePartyContactName() {
         return this.billablePartyContactName;
     }
     
     public void setBillablePartyContactName(String billablePartyContactName) {
         this.billablePartyContactName = billablePartyContactName;
     }
     @Column(name="BILLABLE_PARTY_ADDRESS", unique=false, nullable=true, insertable=true, updatable=true, length=105)

     public String getBillablePartyAddress() {
         return this.billablePartyAddress;
     }
     
     public void setBillablePartyAddress(String billablePartyAddress) {
         this.billablePartyAddress = billablePartyAddress;
     }
     @Column(name="BILLABLE_PARTY_PHONE", unique=false, nullable=true, insertable=true, updatable=true, length=20)

     public String getBillablePartyPhone() {
         return this.billablePartyPhone;
     }
     
     public void setBillablePartyPhone(String billablePartyPhone) {
         this.billablePartyPhone = billablePartyPhone;
     }
     @Column(name="BILLABLE_PARTY_FAX", unique=false, nullable=true, insertable=true, updatable=true, length=20)

     public String getBillablePartyFax() {
         return this.billablePartyFax;
     }
     
     public void setBillablePartyFax(String billablePartyFax) {
         this.billablePartyFax = billablePartyFax;
     }
     @Column(name="BILLABLE_PARTY_EMAIL", unique=false, nullable=true, insertable=true, updatable=true, length=60)

     public String getBillablePartyEmail() {
         return this.billablePartyEmail;
     }
     
     public void setBillablePartyEmail(String billablePartyEmail) {
         this.billablePartyEmail = billablePartyEmail;
     }
     @Column(name="AD_PLANNED_IMPS", unique=false, nullable=true, insertable=true, updatable=true, precision=12, scale=0)

     public Long getAdPlannedImps() {
         return this.adPlannedImps;
     }
     
     public void setAdPlannedImps(Long adPlannedImps) {
         this.adPlannedImps = adPlannedImps;
     }
     @Column(name="IMPRESSION_TO_COUNT", unique=false, nullable=true, insertable=true, updatable=true, precision=1, scale=0)

     public Boolean getImpressionToCount() {
         return this.impressionToCount;
     }
     
     public void setImpressionToCount(Boolean impressionToCount) {
         this.impressionToCount = impressionToCount;
     }
     @Column(name="CREATIVE_FULL_PLAY_LENGTH", unique=false, nullable=false, insertable=true, updatable=true, precision=22, scale=0)

     public BigDecimal getCreativeFullPlayLength() {
         return this.creativeFullPlayLength;
     }
     
     public void setCreativeFullPlayLength(BigDecimal creativeFullPlayLength) {
         this.creativeFullPlayLength = creativeFullPlayLength;
     }
     @Column(name="BILLING_NAME", unique=false, nullable=false, insertable=true, updatable=true, length=30)

     public String getBillingName() {
         return this.billingName;
     }
     
     public void setBillingName(String billingName) {
         this.billingName = billingName;
     }
     @Column(name="VIDEO_PLAY_TIME", unique=false, nullable=false, insertable=true, updatable=true, precision=3, scale=0)

     public short getVideoPlayTime() {
         return this.videoPlayTime;
     }
     
     public void setVideoPlayTime(short videoPlayTime) {
         this.videoPlayTime = videoPlayTime;
     }   
}
