package com.unicast.campaign.interf;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;
import javax.persistence.EntityManager;

public interface IAdMgmtVw {
	
	public List<IAdMgmtVw> executeQuery(EntityManager entityManager, String where, String order);
	
	public Integer getAdId();
    public void setAdId(Integer adId);
    public Long getCreativeId();
    public void setCreativeId(Long creativeId);
    public String getCreativeName();
    public void setCreativeName(String creativeName);
    public Integer getPlacementId();
    public void setPlacementId(Integer placementId);
    public String getPlacementName();
    public void setPlacementName(String placementName);
    public short getCampaignId();
    public void setCampaignId(short campaignId);
    public String getCampaignName();
    public void setCampaignName(String campaignName);
    public Date getCampaignStartDate();
    public void setCampaignStartDate(Date campaignStartDate);
    public Date getCampaignEndDate();
    public void setCampaignEndDate(Date campaignEndDate);
    public String getCampaignPo();
    public void setCampaignPo(String campaignPo);
    public short getPublisherId();
    public void setPublisherId(short publisherId);
    public String getPublisherName();
    public void setPublisherName(String publisherName);
    public short getAdvertiserId();
    public void setAdvertiserId(short advertiserId);
    public String getAdvertiserName();
    public void setAdvertiserName(String advertiserName);
    public short getAgencyId();
    public void setAgencyId(short agencyId);
    public String getAgencyName();
    public void setAgencyName(String agencyName);
    public String getBillablePartyBusType();
    public void setBillablePartyBusType(String billablePartyBusType);
    public String getVwptSalesManager();
    public void setVwptSalesManager(String vwptSalesManager);
    public String getVwptSalesLocation();
    public void setVwptSalesLocation(String vwptSalesLocation);
    public BigDecimal getVwptCsrId();
    public void setVwptCsrId(BigDecimal vwptCsrId);
    public String getVwptCsrName();
    public void setVwptCsrName(String vwptCsrName);
    public Long getPlacementCap();
    public void setPlacementCap(Long placementCap);
    public Date getPlacementStartDate();
    public void setPlacementStartDate(Date placementStartDate);
    public Date getPlacementEndDate();
    public void setPlacementEndDate(Date placementEndDate);
    public String getCreativeProductGroup();
    public void setCreativeProductGroup(String creativeProductGroup);
    public String getCreativeFormat();
    public void setCreativeFormat(String creativeFormat);
    public String getCreativeTechnologyType();
    public void setCreativeTechnologyType(String creativeTechnologyType);
    public BigDecimal getCreativeFileSize();
    public void setCreativeFileSize(BigDecimal creativeFileSize);
    public BigDecimal getCreativeCpm();
    public void setCreativeCpm(BigDecimal creativeCpm);
    public String getBillablePartyContactName();
    public void setBillablePartyContactName(String billablePartyContactName);
    public String getBillablePartyAddress();
    public void setBillablePartyAddress(String billablePartyAddress);
    public String getBillablePartyPhone();
    public void setBillablePartyPhone(String billablePartyPhone);
    public String getBillablePartyFax();
    public void setBillablePartyFax(String billablePartyFax);
    public String getBillablePartyEmail();
    public void setBillablePartyEmail(String billablePartyEmail);
    public Long getAdPlannedImps();
    public void setAdPlannedImps(Long adPlannedImps);
    public Boolean getImpressionToCount();
    public void setImpressionToCount(Boolean impressionToCount);
    public BigDecimal getCreativeFullPlayLength();
    public void setCreativeFullPlayLength(BigDecimal creativeFullPlayLength);
    public String getBillingName();
    public void setBillingName(String billingName);
    public short getVideoPlayTime();  
    public void setVideoPlayTime(short videoPlayTime);
  
}
