package de.laliluna.library;
// Generated by MyEclipse - Hibernate Tools



/**
 * Book generated by MyEclipse - Hibernate Tools
 */
public class Book extends AbstractBook implements java.io.Serializable {

	private Customer customer; 
    //@Override
	public String toString() {
		
		return "Book:  " + getId()+" title: "+getTitle()+" author: "+getAuthor() + " borrowed to: "+getCustomer(); 
	}

	public Customer getCustomer() {
		return customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	/**
     * Simple constructor of Book instances.
     */
    public Book()
    {
    }

    /**
     * Constructor of Book instances given a simple primary key.
     * @param id
     */
    public Book(java.lang.Integer id)
    {
        super(id);
    }

    /* Add customized code below */
}
