package nl.test.domain;
// Generated Sep 12, 2007 8:46:02 AM by Hibernate Tools 3.2.0.b9


import java.util.HashSet;
import java.util.Set;

/**
 * TestRateOwner generated by hbm2java
 */
public class TestRateOwner  implements java.io.Serializable {

    /* The serialVersionUID. */
    private static final long serialVersionUID = 1L;
    

     private Long id;
     private String naam;
     private Set<TestExchangeRate> rates = new HashSet<TestExchangeRate>(0);


    /** default constructor. */
    public TestRateOwner() {
    } 
   
    /**
      * gets the id.
      * @return id
      */
    
    public Long getId() {
        return this.id;
    }
    /**
      * sets the id.
      * @param id to set
      */ 
    public void setId(final Long id) {
        this.id = id;
    }
    /**
      * gets the naam.
      * @return naam
      */
    
    public String getNaam() {
        return this.naam;
    }
    /**
      * sets the naam.
      * @param naam to set
      */ 
    public void setNaam(final String naam) {
        this.naam = naam;
    }
    /**
      * gets the rates.
      * @return rates
      */
    
    public Set<TestExchangeRate> getRates() {
        return this.rates;
    }
    /**
      * sets the rates.
      * @param rates to set
      */ 
    public void setRates(final Set<TestExchangeRate> rates) {
        this.rates = rates;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((id == null) ? 0 : id.hashCode());
        return result;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public boolean equals(final Object obj) {
        if (this == obj) {
            return true;
        }

        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final TestRateOwner other = (TestRateOwner) obj;
        if (id == null) {
            return false;
        } else if (!id.equals(other.getId())) {
            return false;
        }
        return true;
    }

}


