package nl.test.domain;
// Generated Sep 12, 2007 8:46:02 AM by Hibernate Tools 3.2.0.b9


import java.math.BigDecimal;

/**
 * TestExchangeRate generated by hbm2java
 */
public class TestExchangeRate  implements java.io.Serializable {

    /* The serialVersionUID. */
    private static final long serialVersionUID = 1L;
    

     private Long id;
     private BigDecimal rate;
     private TestRateOwner owner;


    /** default constructor. */
    public TestExchangeRate() {
    } 
   
    /**
      * gets the id.
      * @return id
      */
    
    public Long getId() {
        return this.id;
    }
    /**
      * sets the id.
      * @param id to set
      */ 
    public void setId(final Long id) {
        this.id = id;
    }
    /**
      * gets the rate.
      * @return rate
      */
    
    public BigDecimal getRate() {
        return this.rate;
    }
    /**
      * sets the rate.
      * @param rate to set
      */ 
    public void setRate(final BigDecimal rate) {
        this.rate = rate;
    }
    /**
      * gets the owner.
      * @return owner
      */
    
    public TestRateOwner getOwner() {
        return this.owner;
    }
    /**
      * sets the owner.
      * @param owner to set
      */ 
    public void setOwner(final TestRateOwner owner) {
        this.owner = owner;
    }
    /**
     * {@inheritDoc}
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((id == null) ? 0 : id.hashCode());
        return result;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public boolean equals(final Object obj) {
        if (this == obj) {
            return true;
        }

        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final TestExchangeRate other =  (TestExchangeRate) obj;
        if (id == null) {
            return false;
        } else if (!id.equals(other.getId())) {
            return false;
        }
        return true;
    }

}


