package com.tecnotree.upc.hibernate.entity.standard;

import javax.persistence.Embeddable;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.xml.bind.annotation.XmlTransient;

/**
 * ProductTResourceId generated by MyEclipse Persistence Tools
 */
@Embeddable
public class ProductTResourceId implements java.io.Serializable {

	// Fields

	private Product product;

	private Resource resource;

	// Constructors

	/** default constructor */
	public ProductTResourceId() {
	}

	/** full constructor */
	public ProductTResourceId(Product product, Resource resource) {
		this.product = product;
		this.resource = resource;
	}
	// Property accessors
	@ManyToOne
	@XmlTransient
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}
	@ManyToOne
	public Resource getResource() {
		return this.resource;
	}

	public void setResource(Resource resource) {
		this.resource = resource;
	}
	

}