package com.tecnotree.upc.hibernate.entity.standard;

import javax.persistence.AssociationOverride;
import javax.persistence.AssociationOverrides;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

import org.hibernate.annotations.DynamicUpdate;
import org.hibernate.annotations.SelectBeforeUpdate;
 
/**
 * ProductTResource generated by MyEclipse Persistence Tools
 */
@XmlRootElement(name = "productTResource")
@Entity
	@Table(name = "PRODUCT_T_RESOURCE") 
	@AssociationOverrides({
		@AssociationOverride(name = "id.resource", joinColumns = @JoinColumn(name = "RESOURCE_ID")),
		@AssociationOverride(name = "id.product", joinColumns = @JoinColumn(name = "PRODUCT_ID")) })
		@SelectBeforeUpdate
		@DynamicUpdate
public class ProductTResource implements java.io.Serializable {

	// Fields

	private ProductTResourceId id;
	
	private Product product;

	private Resource resource;

	private DependencyType dependencyType;

	// Constructors

	/** default constructor */
	public ProductTResource() {
	}


	/** full constructor */
	public ProductTResource(ProductTResourceId id, DependencyType dependencyType) {
		this.id = id;
		this.dependencyType = dependencyType;
	}


	// Property accessors
	@EmbeddedId
	@XmlElement(name="associatedResource")
	public ProductTResourceId getId() {
		return this.id;
	}
	public void setId(ProductTResourceId id) {
		this.id = id;
	}
	
	@Transient
	@XmlTransient
	public Resource getResource() {
		return getId().getResource();
	}


	public void setResource(Resource resource) {
		getId().getResource();
	}

	@Column(name = "DEPENDENCY_TYPE", length = 50)
	public String getDependencyType() {
		return this.dependencyType;
	}

	public void setDependencyType(String dependencyType) {
		this.dependencyType = dependencyType;
	}
	@Transient
	@XmlTransient
	public Product getProduct() {
		return getId().getProduct();
	}

	public void setProduct(Product product) {
		getId().setProduct(product);
	}
}