// default package


/**
 * Bref generated by hbm2java
 */
public class Bref  implements java.io.Serializable {

    // Fields    

    private java.lang.Integer BranchNum;
    private java.lang.String Bname;
    private java.lang.String Phone;
    private java.lang.String ShortName;
    private java.lang.String Street;
    private java.lang.String BranchType;
    private java.lang.String Pcode;
    private java.math.BigDecimal FloorArea;
    private java.util.Date DateOpened;
    private java.util.Date DateActive;
    private java.util.Date DateClosed;
    private java.util.Date DateInactive;
    private java.util.Date DateUpdated;
    private java.lang.String UserId;
    private java.lang.String City;
    private java.lang.String District;
    private java.lang.String Country;
    private java.lang.String State;
    private java.lang.String Fax1Num;
    private java.lang.String Fax2Num;
    private java.lang.String BankName;
    private java.lang.String BankStreet;
    private java.lang.String BankCity;
    private java.lang.String BankBranch;
    private java.lang.String BankAcct;
    private java.lang.String BankBsb;
    private java.lang.String VatRegnum;
    private java.math.BigDecimal CashFloat;
    private java.lang.String ProviderNum;
    private java.lang.String RecStat;


    // Constructors

    /** default constructor */
    public Bref() {
    }
    
    /** constructor with id */
    public Bref(java.lang.Integer BranchNum) {
        this.BranchNum = BranchNum;
    }
    
    

    // Property accessors
    /**
     */
   public java.lang.Integer getBranchNum () {
        return this.BranchNum;
    }
    
   public void setBranchNum (java.lang.Integer BranchNum) {
        this.BranchNum = BranchNum;
    }
    /**
     */
   public java.lang.String getBname () {
        return this.Bname;
    }
    
   public void setBname (java.lang.String Bname) {
        this.Bname = Bname;
    }
    /**
     */
   public java.lang.String getPhone () {
        return this.Phone;
    }
    
   public void setPhone (java.lang.String Phone) {
        this.Phone = Phone;
    }
    /**
     */
   public java.lang.String getShortName () {
        return this.ShortName;
    }
    
   public void setShortName (java.lang.String ShortName) {
        this.ShortName = ShortName;
    }
    /**
     */
   public java.lang.String getStreet () {
        return this.Street;
    }
    
   public void setStreet (java.lang.String Street) {
        this.Street = Street;
    }
    /**
     */
   public java.lang.String getBranchType () {
        return this.BranchType;
    }
    
   public void setBranchType (java.lang.String BranchType) {
        this.BranchType = BranchType;
    }
    /**
     */
   public java.lang.String getPcode () {
        return this.Pcode;
    }
    
   public void setPcode (java.lang.String Pcode) {
        this.Pcode = Pcode;
    }
    /**
     */
   public java.math.BigDecimal getFloorArea () {
        return this.FloorArea;
    }
    
   public void setFloorArea (java.math.BigDecimal FloorArea) {
        this.FloorArea = FloorArea;
    }
    /**
     */
   public java.util.Date getDateOpened () {
        return this.DateOpened;
    }
    
   public void setDateOpened (java.util.Date DateOpened) {
        this.DateOpened = DateOpened;
    }
    /**
     */
   public java.util.Date getDateActive () {
        return this.DateActive;
    }
    
   public void setDateActive (java.util.Date DateActive) {
        this.DateActive = DateActive;
    }
    /**
     */
   public java.util.Date getDateClosed () {
        return this.DateClosed;
    }
    
   public void setDateClosed (java.util.Date DateClosed) {
        this.DateClosed = DateClosed;
    }
    /**
     */
   public java.util.Date getDateInactive () {
        return this.DateInactive;
    }
    
   public void setDateInactive (java.util.Date DateInactive) {
        this.DateInactive = DateInactive;
    }
    /**
     */
   public java.util.Date getDateUpdated () {
        return this.DateUpdated;
    }
    
   public void setDateUpdated (java.util.Date DateUpdated) {
        this.DateUpdated = DateUpdated;
    }
    /**
     */
   public java.lang.String getUserId () {
        return this.UserId;
    }
    
   public void setUserId (java.lang.String UserId) {
        this.UserId = UserId;
    }
    /**
     */
   public java.lang.String getCity () {
        return this.City;
    }
    
   public void setCity (java.lang.String City) {
        this.City = City;
    }
    /**
     */
   public java.lang.String getDistrict () {
        return this.District;
    }
    
   public void setDistrict (java.lang.String District) {
        this.District = District;
    }
    /**
     */
   public java.lang.String getCountry () {
        return this.Country;
    }
    
   public void setCountry (java.lang.String Country) {
        this.Country = Country;
    }
    /**
     */
   public java.lang.String getState () {
        return this.State;
    }
    
   public void setState (java.lang.String State) {
        this.State = State;
    }
    /**
     */
   public java.lang.String getFax1Num () {
        return this.Fax1Num;
    }
    
   public void setFax1Num (java.lang.String Fax1Num) {
        this.Fax1Num = Fax1Num;
    }
    /**
     */
   public java.lang.String getFax2Num () {
        return this.Fax2Num;
    }
    
   public void setFax2Num (java.lang.String Fax2Num) {
        this.Fax2Num = Fax2Num;
    }
    /**
     */
   public java.lang.String getBankName () {
        return this.BankName;
    }
    
   public void setBankName (java.lang.String BankName) {
        this.BankName = BankName;
    }
    /**
     */
   public java.lang.String getBankStreet () {
        return this.BankStreet;
    }
    
   public void setBankStreet (java.lang.String BankStreet) {
        this.BankStreet = BankStreet;
    }
    /**
     */
   public java.lang.String getBankCity () {
        return this.BankCity;
    }
    
   public void setBankCity (java.lang.String BankCity) {
        this.BankCity = BankCity;
    }
    /**
     */
   public java.lang.String getBankBranch () {
        return this.BankBranch;
    }
    
   public void setBankBranch (java.lang.String BankBranch) {
        this.BankBranch = BankBranch;
    }
    /**
     */
   public java.lang.String getBankAcct () {
        return this.BankAcct;
    }
    
   public void setBankAcct (java.lang.String BankAcct) {
        this.BankAcct = BankAcct;
    }
    /**
     */
   public java.lang.String getBankBsb () {
        return this.BankBsb;
    }
    
   public void setBankBsb (java.lang.String BankBsb) {
        this.BankBsb = BankBsb;
    }
    /**
     */
   public java.lang.String getVatRegnum () {
        return this.VatRegnum;
    }
    
   public void setVatRegnum (java.lang.String VatRegnum) {
        this.VatRegnum = VatRegnum;
    }
    /**
     */
   public java.math.BigDecimal getCashFloat () {
        return this.CashFloat;
    }
    
   public void setCashFloat (java.math.BigDecimal CashFloat) {
        this.CashFloat = CashFloat;
    }
    /**
     */
   public java.lang.String getProviderNum () {
        return this.ProviderNum;
    }
    
   public void setProviderNum (java.lang.String ProviderNum) {
        this.ProviderNum = ProviderNum;
    }
    /**
     */
   public java.lang.String getRecStat () {
        return this.RecStat;
    }
    
   public void setRecStat (java.lang.String RecStat) {
        this.RecStat = RecStat;
    }




}