package com.jpmorgan.embo.maintainers.generated;

// Generated 17/06/2008 11:00:40 by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SwiftDocument generated by hbm2java
 */
@Entity
@Table(name = "SWIFT_DOCUMENT", schema = "EMBO")
public class SwiftDocument implements java.io.Serializable {

    private int swiftDocumentId;
    private SwiftMessage swiftMessage;
    private String swiftMessageDescription;
    private Integer swiftRule;
    private Set<SwiftSet> swiftSets = new HashSet<SwiftSet>(0);

    public SwiftDocument() {
    }

    public SwiftDocument(int swiftDocumentId, SwiftMessage swiftMessage) {
        this.swiftDocumentId = swiftDocumentId;
        this.swiftMessage = swiftMessage;
    }

    public SwiftDocument(int swiftDocumentId, SwiftMessage swiftMessage,
            String swiftMessageDescription, Integer swiftRule,
            Set<SwiftSet> swiftSets) {
        this.swiftDocumentId = swiftDocumentId;
        this.swiftMessage = swiftMessage;
        this.swiftMessageDescription = swiftMessageDescription;
        this.swiftRule = swiftRule;
        this.swiftSets = swiftSets;
    }

    @Id
    @Column(name = "SWIFT_DOCUMENT_ID", unique = true, nullable = false, precision = 5, scale = 0)
    public int getSwiftDocumentId() {
        return this.swiftDocumentId;
    }

    public void setSwiftDocumentId(int swiftDocumentId) {
        this.swiftDocumentId = swiftDocumentId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "SWIFT_MESSAGE_ID", nullable = false)
    public SwiftMessage getSwiftMessage() {
        return this.swiftMessage;
    }

    public void setSwiftMessage(SwiftMessage swiftMessage) {
        this.swiftMessage = swiftMessage;
    }

    @Column(name = "SWIFT_MESSAGE_DESCRIPTION", length = 30)
    public String getSwiftMessageDescription() {
        return this.swiftMessageDescription;
    }

    public void setSwiftMessageDescription(String swiftMessageDescription) {
        this.swiftMessageDescription = swiftMessageDescription;
    }

    @Column(name = "SWIFT_RULE", precision = 5, scale = 0)
    public Integer getSwiftRule() {
        return this.swiftRule;
    }

    public void setSwiftRule(Integer swiftRule) {
        this.swiftRule = swiftRule;
    }

    @ManyToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY)
    @JoinTable(name = "SWIFT_MAP", schema = "EMBO", joinColumns = { @JoinColumn(name = "SWIFT_DOCUMENT_ID", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "SWIFT_MESSAGE_ID", nullable = false, updatable = false) })
    public Set<SwiftSet> getSwiftSets() {
        return this.swiftSets;
    }

    public void setSwiftSets(Set<SwiftSet> swiftSets) {
        this.swiftSets = swiftSets;
    }

}
