package com.jpmorgan.embo.maintainers.generated;

// Generated 17/06/2008 11:00:40 by Hibernate Tools 3.2.1.GA

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SwiftSetId generated by hbm2java
 */
@Embeddable
public class SwiftSetId implements java.io.Serializable {

    private int swiftMessageId;
    private int orderNumber;

    public SwiftSetId() {
    }

    public SwiftSetId(int swiftMessageId, int orderNumber) {
        this.swiftMessageId = swiftMessageId;
        this.orderNumber = orderNumber;
    }

    @Column(name = "SWIFT_MESSAGE_ID", nullable = false, precision = 5, scale = 0)
    public int getSwiftMessageId() {
        return this.swiftMessageId;
    }

    public void setSwiftMessageId(int swiftMessageId) {
        this.swiftMessageId = swiftMessageId;
    }

    @Column(name = "ORDER_NUMBER", nullable = false, precision = 5, scale = 0)
    public int getOrderNumber() {
        return this.orderNumber;
    }

    public void setOrderNumber(int orderNumber) {
        this.orderNumber = orderNumber;
    }

    public boolean equals(Object other) {
        if ((this == other))
            return true;
        if ((other == null))
            return false;
        if (!(other instanceof SwiftSetId))
            return false;
        SwiftSetId castOther = (SwiftSetId) other;

        return (this.getSwiftMessageId() == castOther.getSwiftMessageId())
                && (this.getOrderNumber() == castOther.getOrderNumber());
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + this.getSwiftMessageId();
        result = 37 * result + this.getOrderNumber();
        return result;
    }

}
