// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: EntityEmbeddable.vsl in andromda-ejb3-cartridge.
//
package ru.cti.oss.iptv.resource.logical;

/**
 * Autogenerated POJO EJB class for Movie containing the
 * bulk of the entity implementation.
 *
 * This is autogenerated by AndroMDA using the EJB3
 * cartridge.
 *
 * DO NOT MODIFY this class.
 *
 * 
 *
 */
@javax.persistence.Entity
@javax.persistence.Table(name = "MOVIE")
@org.hibernate.annotations.Cache(usage = org.hibernate.annotations.CacheConcurrencyStrategy.TRANSACTIONAL)
@javax.persistence.NamedQueries
({
    @javax.persistence.NamedQuery(name = "Movie.findAll", query = "select movie from Movie AS movie"),
    @javax.persistence.NamedQuery(name = "Movie.findByCategory", query = "select movie from Movie as movie join movie.categories cat where cat.id = :category")
})
public class Movie
    extends ru.cti.oss.iptv.resource.logical.MediaContent
    implements java.io.Serializable
{

    private static final long serialVersionUID = -3620386098840149390L;

    // ----------- Attribute Definitions ------------

    private java.lang.String actors;
    private java.lang.String director;
    private java.lang.String starRating;
    private java.lang.String studio;
    private java.util.Date year;
    private java.lang.Long duration;
    private ru.cti.oss.iptv.Image poster = new ru.cti.oss.iptv.Image();
    private java.lang.String country;
    private ru.cti.oss.iptv.resource.logical.ScreenFormat screenFormat;


    // --------- Relationship Definitions -----------

    private java.util.Set<ru.cti.oss.iptv.resource.logical.MediaAsset> previews = new java.util.TreeSet<ru.cti.oss.iptv.resource.logical.MediaAsset>();
    private ru.cti.oss.iptv.resource.logical.MovieCategory movieCategory;

    // ---- Manageable Display Attributes (Transient) -----


    // --------------- Constructors -----------------

    /**
     * Default empty constructor
     */
    public Movie() {}

    /**
     * Implementation for the constructor with all POJO attributes except auto incremented identifiers.
     * This method sets all POJO fields defined in this class to the values provided by
     * the parameters.
     *
     * @param name Value for the name property
     * @param description Value for the description property
     * @param status Value for the status property
     * @param actors Value for the actors property
     * @param director Value for the director property
     * @param starRating Value for the starRating property
     * @param studio Value for the studio property
     * @param year Value for the year property
     * @param duration Value for the duration property
     * @param poster Value for the poster property
     * @param country Value for the country property
     * @param screenFormat Value for the screenFormat property
     */
    public Movie(java.lang.String name, java.lang.String description, ru.cti.oss.cbe.datatypes.LifeCycleState status, java.lang.String actors, java.lang.String director, java.lang.String starRating, java.lang.String studio, java.util.Date year, java.lang.Long duration, ru.cti.oss.iptv.Image poster, java.lang.String country, ru.cti.oss.iptv.resource.logical.ScreenFormat screenFormat)
    {
        super(name, description, status);
        setName(name);
        setDescription(description);
        setStatus(status);
        setActors(actors);
        setDirector(director);
        setStarRating(starRating);
        setStudio(studio);
        setYear(year);
        setDuration(duration);
        setPoster(poster);
        setCountry(country);
        setScreenFormat(screenFormat);
    }

    /**
     * Constructor with all POJO attribute values and CMR relations.
     *
     * @param name Value for the name property
     * @param description Value for the description property
     * @param status Value for the status property
     * @param actors Value for the actors property
     * @param director Value for the director property
     * @param starRating Value for the starRating property
     * @param studio Value for the studio property
     * @param year Value for the year property
     * @param duration Value for the duration property
     * @param poster Value for the poster property
     * @param country Value for the country property
     * @param screenFormat Value for the screenFormat property
     * @param previews Value for the previews relation
     * @param movieCategory Value for the movieCategory relation
     */
    public Movie(java.lang.String name, java.lang.String description, ru.cti.oss.cbe.datatypes.LifeCycleState status, java.lang.String actors, java.lang.String director, java.lang.String starRating, java.lang.String studio, java.util.Date year, java.lang.Long duration, ru.cti.oss.iptv.Image poster, java.lang.String country, ru.cti.oss.iptv.resource.logical.ScreenFormat screenFormat, java.util.Set<ru.cti.oss.iptv.resource.logical.MediaAsset> previews, ru.cti.oss.iptv.resource.logical.MovieCategory movieCategory)
    {
        setName(name);
        setDescription(description);
        setStatus(status);
        setActors(actors);
        setDirector(director);
        setStarRating(starRating);
        setStudio(studio);
        setYear(year);
        setDuration(duration);
        setPoster(poster);
        setCountry(country);
        setScreenFormat(screenFormat);

        setPreviews(previews);
        setMovieCategory(movieCategory);
    }


    // -------- Attribute Accessors ----------

    /**
     * Get the actors property.
     * 
     * @return java.lang.String The value of actors
     */
    	@javax.persistence.Column(name = "ACTORS", insertable = true, updatable = true)
    public java.lang.String getActors()
    {
        return actors;
    }

    /**
     * Set the actors property.
     * @param value the new value
     */
    public void setActors(java.lang.String value)
    {
        this.actors = value;
    }

    /**
     * Get the director property.
     * 
     * @return java.lang.String The value of director
     */
    	@javax.persistence.Column(name = "DIRECTOR", insertable = true, updatable = true)
    public java.lang.String getDirector()
    {
        return director;
    }

    /**
     * Set the director property.
     * @param value the new value
     */
    public void setDirector(java.lang.String value)
    {
        this.director = value;
    }

    /**
     * Get the starRating property.
     * 
     * @return java.lang.String The value of starRating
     */
    	@javax.persistence.Column(name = "STAR_RATING", insertable = true, updatable = true)
    public java.lang.String getStarRating()
    {
        return starRating;
    }

    /**
     * Set the starRating property.
     * @param value the new value
     */
    public void setStarRating(java.lang.String value)
    {
        this.starRating = value;
    }

    /**
     * Get the studio property.
     * 
     * @return java.lang.String The value of studio
     */
    	@javax.persistence.Column(name = "STUDIO", insertable = true, updatable = true)
    public java.lang.String getStudio()
    {
        return studio;
    }

    /**
     * Set the studio property.
     * @param value the new value
     */
    public void setStudio(java.lang.String value)
    {
        this.studio = value;
    }

    /**
     * Get the year property.
     * 
     * @return java.util.Date The value of year
     */
    	@javax.persistence.Column(name = "YEAR", insertable = true, updatable = true)
    @javax.persistence.Temporal(javax.persistence.TemporalType.TIMESTAMP)
    public java.util.Date getYear()
    {
        return year;
    }

    /**
     * Set the year property.
     * @param value the new value
     */
    public void setYear(java.util.Date value)
    {
        this.year = value;
    }

    /**
     * Get the duration property.
     * 
     * @return java.lang.Long The value of duration
     */
    	@javax.persistence.Column(name = "DURATION", nullable = false, insertable = true, updatable = true)
    public java.lang.Long getDuration()
    {
        return duration;
    }

    /**
     * Set the duration property.
     * @param value the new value
     */
    public void setDuration(java.lang.Long value)
    {
        this.duration = value;
    }

    /**
     * Get the poster property.
     * 
     * @return ru.cti.oss.iptv.Image The value of poster
     */
    @javax.persistence.Embedded
    @javax.persistence.AttributeOverrides
    ({
        @javax.persistence.AttributeOverride(name = "width", column = @javax.persistence.Column(name = "POSTER_WIDTH", insertable = true, updatable = true)),
        @javax.persistence.AttributeOverride(name = "height", column = @javax.persistence.Column(name = "POSTER_HEIGHT", insertable = true, updatable = true)),
        @javax.persistence.AttributeOverride(name = "size", column = @javax.persistence.Column(name = "POSTER_SIZE", insertable = true, updatable = true)),
        @javax.persistence.AttributeOverride(name = "contentType", column = @javax.persistence.Column(name = "POSTER_CONTENT_TYPE", insertable = true, updatable = true)),
        @javax.persistence.AttributeOverride(name = "data", column = @javax.persistence.Column(name = "POSTER_DATA", insertable = true, updatable = true))
    })
    public ru.cti.oss.iptv.Image getPoster()
    {
        return poster;
    }

    /**
     * Set the poster property.
     * @param value the new value
     */
    public void setPoster(ru.cti.oss.iptv.Image value)
    {
        this.poster = value;
    }

    /**
     * Get the country property.
     * 
     * @return java.lang.String The value of country
     */
    	@javax.persistence.Column(name = "COUNTRY", insertable = true, updatable = true)
    public java.lang.String getCountry()
    {
        return country;
    }

    /**
     * Set the country property.
     * @param value the new value
     */
    public void setCountry(java.lang.String value)
    {
        this.country = value;
    }

    /**
     * Get the screenFormat property.
     * 
     * @return ru.cti.oss.iptv.resource.logical.ScreenFormat The value of screenFormat
     */
    	@javax.persistence.Column(name = "SCREEN_FORMAT", insertable = true, updatable = true)
    @javax.persistence.Enumerated(javax.persistence.EnumType.STRING)
    public ru.cti.oss.iptv.resource.logical.ScreenFormat getScreenFormat()
    {
        return screenFormat;
    }

    /**
     * Set the screenFormat property.
     * @param value the new value
     */
    public void setScreenFormat(ru.cti.oss.iptv.resource.logical.ScreenFormat value)
    {
        this.screenFormat = value;
    }


    // ------------- Relations ------------------

    /**
     * Get the previews Collection
     *
     * @return java.util.Set<ru.cti.oss.iptv.resource.logical.MediaAsset>
     */
    @javax.persistence.ManyToMany()
    @javax.persistence.JoinTable
    (
        name = "MOVIES2PREVIEWS",
        joinColumns = {@javax.persistence.JoinColumn(name = "MOVIE_IDC", referencedColumnName = "ID")},
        inverseJoinColumns = {@javax.persistence.JoinColumn(name = "MEDIA_ASSET_IDC", referencedColumnName = "ID")}
    )
    @org.hibernate.annotations.Cache(usage = org.hibernate.annotations.CacheConcurrencyStrategy.TRANSACTIONAL)
    public java.util.Set<ru.cti.oss.iptv.resource.logical.MediaAsset> getPreviews()
    {
        return this.previews;
    }

    /**
     * Set the previews
     *
     * @param previews
     */
    public void setPreviews (java.util.Set<ru.cti.oss.iptv.resource.logical.MediaAsset> previews)
    {
        this.previews = previews;
    }

    /**
     * Add MediaAsset
     *
     * @param mediaAsset
     */

    public void addToPreviews(ru.cti.oss.iptv.resource.logical.MediaAsset mediaAsset)
    {
        if (mediaAsset == null ) return;
        this.getPreviews().add(mediaAsset);
    }

    /**
     * Remove MediaAsset
     *
     * @param mediaAsset
     */

    public void removeFromPreviews (ru.cti.oss.iptv.resource.logical.MediaAsset mediaAsset)
    {
        if (mediaAsset == null ) return;
        this.getPreviews().remove(mediaAsset);
    }

    /**
     * Get the movieCategory
     *
     * @return ru.cti.oss.iptv.resource.logical.MovieCategory
     */
    @javax.persistence.ManyToOne()
    @javax.persistence.JoinColumn(name = "MOVIECATEGORY")
    public ru.cti.oss.iptv.resource.logical.MovieCategory getMovieCategory()
    {
        return this.movieCategory;
    }

   /**
    * Set the movieCategory
    *
    * @param movieCategory
    */
    public void setMovieCategory(ru.cti.oss.iptv.resource.logical.MovieCategory movieCategory)
    {
        this.movieCategory = movieCategory;
    }

    // -------- Common Methods -----------

    /**
     * Indicates if the argument is of the same type and all values are equal.
     *
     * @param object The target object to compare with
     * @return boolean True if both objects a 'equal'
     */
    public boolean equals(Object object)
    {
        if (this == object)
        {
            return true;
        }
        if (!(object instanceof Movie))
        {
            return false;
        }
        final Movie that = (Movie)object;
        if (this.getId() == null || that.getId() == null || !this.getId().equals(that.getId()))
        {
            return false;
        }
        return true;
    }

    /**
     * Returns a hash code value for the object
     *
     * @return int The hash code value
     */
    public int hashCode()
    {
        int hashCode = super.hashCode();
        hashCode = 29 * hashCode + (getId() == null ? 0 : getId().hashCode());

        return hashCode;
    }

    /**
     * Returns a String representation of the object
     *
     * @return String Textual representation of the object displaying name/value pairs for all attributes
     */
    public String toString()
    {
        StringBuilder sb = new StringBuilder();
        sb.append("Movie(=");
        sb.append(super.toString());
        sb.append("actors: ");
        sb.append(getActors());
        sb.append(", director: ");
        sb.append(getDirector());
        sb.append(", starRating: ");
        sb.append(getStarRating());
        sb.append(", studio: ");
        sb.append(getStudio());
        sb.append(", year: ");
        sb.append(getYear());
        sb.append(", duration: ");
        sb.append(getDuration());
        sb.append(", poster: ");
		if (getPoster()!=null)
		    sb.append(getPoster().toString());
	    else
		    sb.append("null");
        sb.append(", country: ");
        sb.append(getCountry());
        sb.append(", screenFormat: ");
        sb.append(getScreenFormat());
        sb.append(")");
        return sb.toString();
    }

}