package com.myasd.db.ee;
// Generated Jan 11, 2018 2:59:20 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;

/**
 * HibernateTest generated by hbm2java
 */
@Entity
@Table(name = "hibernate_test", schema = "dbo", catalog = "mydb")
public class HibernateTest implements java.io.Serializable {

	private String tableId;
	private String tableValue;

	public HibernateTest() {
	}

	public HibernateTest(String tableValue) {
		this.tableValue = tableValue;
	}

	@GenericGenerator(name = "generator", strategy = "guid")
	@Id
	@GeneratedValue(generator = "generator")

	@Column(name = "TableID", unique = true, nullable = false, length = 36)
	public String getTableId() {
		return this.tableId;
	}

	public void setTableId(String tableId) {
		this.tableId = tableId;
	}

	@Column(name = "TableValue", nullable = false, length = 50)
	public String getTableValue() {
		return this.tableValue;
	}

	public void setTableValue(String tableValue) {
		this.tableValue = tableValue;
	}

}
