// default package
// Generated 27-nov-2020 16:20:15 by Hibernate Tools 5.4.24.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * HibernateTest generated by hbm2java
 */
@Entity
@Table(name="hibernate_test"
)
public class HibernateTest  implements java.io.Serializable {


     private String tableId;
     private String tableValue;

    public HibernateTest() {
    }

    public HibernateTest(String tableId, String tableValue) {
       this.tableId = tableId;
       this.tableValue = tableValue;
    }
   
     @Id 

    
    @Column(name="TableID", unique=true, nullable=false, length=36)
    public String getTableId() {
        return this.tableId;
    }
    
    public void setTableId(String tableId) {
        this.tableId = tableId;
    }

    
    @Column(name="TableValue", nullable=false, length=50)
    public String getTableValue() {
        return this.tableValue;
    }
    
    public void setTableValue(String tableValue) {
        this.tableValue = tableValue;
    }




}


