package de.infracore.hbm;
// Generated 05.02.2006 18:31:38 by Hibernate Tools 3.1.0.beta4

import java.util.Date;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;


/**
 * Address generated by hbm2java
 */
@Entity
@Table(name="address"
    ,catalog=""
)

public class Address extends de.infracore.hbm.Entity implements java.io.Serializable {


    // Fields    

     private String country;
     private String state;
     private String postcode;
     private String city;
     private String street;
     private String telPrivat;
     private String telMobil;
     private String telBusiness;


    // Constructors

    /** default constructor */
    public Address() {
    }

	/** minimal constructor */
    public Address(long id) {
        super(id);        
    }
    
    /** full constructor */
    public Address(long id, Entity entity, Byte ownerAccess, Byte publicAccess, Integer flags, Date creationdate, Date lastchange, Set<Entity> entities, Set<SysUsecase> sysUsecases, Set<SysMessage> sysMessages, Set<Container> containersForId, Set<Account> accounts, Set<Point> points, Set<Container> containersForIdEntity, Set<Image> images, Set<Price> prices, Set<Commentary> commentaries, Set<Person> persons, Set<Area> areas, Set<SysLayout> sysLayouts, Set<Category> categories, Set<Advertising> advertisings, Set<Address> addresses, Set<Usergroup> usergroups, Set<Path> paths, Set<Pixelmap> pixelmaps, Set<Rating> ratings, Set<Link> links, Set<SysComponent> sysComponents, Set<Article> articles, Set<Task> tasks, Set<SysFile> sysFiles, Set<SysSite> sysSites, Set<Choice> choices, Set<Trace> traces, Set<Adorder> adorders, Set<Query> queries, Set<Roles> roleses, Set<DateTime> dateTimes, Set<Transfer> transfers, Set<SysTypes> sysTypeses, String country, String state, String postcode, String city, String street, String telPrivat, String telMobil, String telBusiness) {
        super(id, entity, ownerAccess, publicAccess, flags, creationdate, lastchange, entities, sysUsecases, sysMessages, containersForId, accounts, points, containersForIdEntity, images, prices, commentaries, persons, areas, sysLayouts, categories, advertisings, addresses, usergroups, paths, pixelmaps, ratings, links, sysComponents, articles, tasks, sysFiles, sysSites, choices, traces, adorders, queries, roleses, dateTimes, transfers, sysTypeses);        
        this.country = country;
        this.state = state;
        this.postcode = postcode;
        this.city = city;
        this.street = street;
        this.telPrivat = telPrivat;
        this.telMobil = telMobil;
        this.telBusiness = telBusiness;
    }
    

   
    // Property accessors
    @Column(name="country", unique=false, nullable=true, insertable=true, updatable=true, length=40)

    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }
    @Column(name="state", unique=false, nullable=true, insertable=true, updatable=true, length=40)

    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }
    @Column(name="postcode", unique=false, nullable=true, insertable=true, updatable=true, length=20)

    public String getPostcode() {
        return this.postcode;
    }
    
    public void setPostcode(String postcode) {
        this.postcode = postcode;
    }
    @Column(name="city", unique=false, nullable=true, insertable=true, updatable=true, length=80)

    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    @Column(name="street", unique=false, nullable=true, insertable=true, updatable=true, length=80)

    public String getStreet() {
        return this.street;
    }
    
    public void setStreet(String street) {
        this.street = street;
    }
    @Column(name="tel_privat", unique=false, nullable=true, insertable=true, updatable=true, length=40)

    public String getTelPrivat() {
        return this.telPrivat;
    }
    
    public void setTelPrivat(String telPrivat) {
        this.telPrivat = telPrivat;
    }
    @Column(name="tel_mobil", unique=false, nullable=true, insertable=true, updatable=true, length=40)

    public String getTelMobil() {
        return this.telMobil;
    }
    
    public void setTelMobil(String telMobil) {
        this.telMobil = telMobil;
    }
    @Column(name="tel_business", unique=false, nullable=true, insertable=true, updatable=true, length=40)

    public String getTelBusiness() {
        return this.telBusiness;
    }
    
    public void setTelBusiness(String telBusiness) {
        this.telBusiness = telBusiness;
    }
   








}
