package com.arvato.hibernate.entities;
// Generated 06.10.2006 20:21:37 by Hibernate Tools 3.2.0.beta6a


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tras001 generated by hbm2java
 */
@Entity
@Table(name="vras001_v025"
    ,schema="dbo"
    ,catalog="DSAM000"
)
public class Tras001 
implements java.io.Serializable

 {

    // Fields    

     private Tras001Id id;
     private Tras070 tras070;
     private Tras197 tras197;
     private Tras095 tras095;
     private Tras160 tras160;
     private Tras039 tras039ByTras001470305864;
     private Tras198 tras198;
     private Tras039 tras039ByTras001710306719;
     private Tras024 tras024ByTras001614306377;
     private Tras039 tras039ByTras001454305807;
     private Tras002 tras002;
     private Tras039 tras039ByTras001422305693;
     private Tras207 tras207;
     private Tras062 tras062;
     private Tras071 tras071;
     private Tras039 tras039ByTras001486305921;
     private Tras159 tras159;
     private Tras196 tras196;
     private Tras039 tras039ByTras001438305750;
     private Tras024 tras024ByTras001582306263;
     private Tras025 tras025;
     private Tras069 tras069;
     private String technique;
     private String barcode;
     private String origProdNo;
     private String raasInitDate;
     private String raasInitUser;
     private String firstReleaseDate;
     private short configSet;
     private String subTitle;
     private String backLine;
     private Short noOfSides;
     private char isComplete;
     private short editCount;
     private String explanation;
     private String merchType;
     private String merchSize;
     private String merchColour;
     private Short generateSkip;
     private Date completeStamp;
     private String completeUser;
     private Date logModStamp;
     private String logModUser;
     private String CLine;
     private Character isLocalFlag;
     private Character generatedByGridFlag;
     private String gridNo;
     private Character isCopyControlled;
     private String audioFormat;
     private String imageFormat;
     private String gasFamilyId;
     private String catlgCoreId;
     private String catlgPfixId;
     private String affiliateId;
     private Date firstCompleteStamp;
     private String firstCompleteUser;
     private String gdsCatlgPfixId;
     private String gdsAffiliateId;
     private Date modStamp;
     private char modFlag;
     private String modUser;
     private Set<Tras009> tras009s = new HashSet<Tras009>(0);
     private Set<Tras003> tras003s = new HashSet<Tras003>(0);
     private Set<Tras203> tras203s = new HashSet<Tras203>(0);

     // Constructors

    /** default constructor */
    public Tras001() {
    }

	/** minimal constructor */
    public Tras001(Tras001Id id, Tras070 tras070, Tras095 tras095, Tras160 tras160, Tras039 tras039ByTras001470305864, Tras039 tras039ByTras001710306719, Tras024 tras024ByTras001614306377, Tras039 tras039ByTras001454305807, Tras002 tras002, Tras039 tras039ByTras001422305693, Tras062 tras062, Tras071 tras071, Tras039 tras039ByTras001486305921, Tras159 tras159, Tras039 tras039ByTras001438305750, Tras024 tras024ByTras001582306263, Tras025 tras025, Tras069 tras069, String raasInitDate, short configSet, char isComplete, short editCount, Date modStamp, char modFlag, String modUser) {
        this.id = id;
        this.tras070 = tras070;
        this.tras095 = tras095;
        this.tras160 = tras160;
        this.tras039ByTras001470305864 = tras039ByTras001470305864;
        this.tras039ByTras001710306719 = tras039ByTras001710306719;
        this.tras024ByTras001614306377 = tras024ByTras001614306377;
        this.tras039ByTras001454305807 = tras039ByTras001454305807;
        this.tras002 = tras002;
        this.tras039ByTras001422305693 = tras039ByTras001422305693;
        this.tras062 = tras062;
        this.tras071 = tras071;
        this.tras039ByTras001486305921 = tras039ByTras001486305921;
        this.tras159 = tras159;
        this.tras039ByTras001438305750 = tras039ByTras001438305750;
        this.tras024ByTras001582306263 = tras024ByTras001582306263;
        this.tras025 = tras025;
        this.tras069 = tras069;
        this.raasInitDate = raasInitDate;
        this.configSet = configSet;
        this.isComplete = isComplete;
        this.editCount = editCount;
        this.modStamp = modStamp;
        this.modFlag = modFlag;
        this.modUser = modUser;
    }
    /** full constructor */
    public Tras001(Tras001Id id, Tras070 tras070, Tras197 tras197, Tras095 tras095, Tras160 tras160, Tras039 tras039ByTras001470305864, Tras198 tras198, Tras039 tras039ByTras001710306719, Tras024 tras024ByTras001614306377, Tras039 tras039ByTras001454305807, Tras002 tras002, Tras039 tras039ByTras001422305693, Tras207 tras207, Tras062 tras062, Tras071 tras071, Tras039 tras039ByTras001486305921, Tras159 tras159, Tras196 tras196, Tras039 tras039ByTras001438305750, Tras024 tras024ByTras001582306263, Tras025 tras025, Tras069 tras069, String technique, String barcode, String origProdNo, String raasInitDate, String raasInitUser, String firstReleaseDate, short configSet, String subTitle, String backLine, Short noOfSides, char isComplete, short editCount, String explanation, String merchType, String merchSize, String merchColour, Short generateSkip, Date completeStamp, String completeUser, Date logModStamp, String logModUser, String CLine, Character isLocalFlag, Character generatedByGridFlag, String gridNo, Character isCopyControlled, String audioFormat, String imageFormat, String gasFamilyId, String catlgCoreId, String catlgPfixId, String affiliateId, Date firstCompleteStamp, String firstCompleteUser, String gdsCatlgPfixId, String gdsAffiliateId, Date modStamp, char modFlag, String modUser, Set<Tras009> tras009s, Set<Tras003> tras003s, Set<Tras203> tras203s) {
       this.id = id;
       this.tras070 = tras070;
       this.tras197 = tras197;
       this.tras095 = tras095;
       this.tras160 = tras160;
       this.tras039ByTras001470305864 = tras039ByTras001470305864;
       this.tras198 = tras198;
       this.tras039ByTras001710306719 = tras039ByTras001710306719;
       this.tras024ByTras001614306377 = tras024ByTras001614306377;
       this.tras039ByTras001454305807 = tras039ByTras001454305807;
       this.tras002 = tras002;
       this.tras039ByTras001422305693 = tras039ByTras001422305693;
       this.tras207 = tras207;
       this.tras062 = tras062;
       this.tras071 = tras071;
       this.tras039ByTras001486305921 = tras039ByTras001486305921;
       this.tras159 = tras159;
       this.tras196 = tras196;
       this.tras039ByTras001438305750 = tras039ByTras001438305750;
       this.tras024ByTras001582306263 = tras024ByTras001582306263;
       this.tras025 = tras025;
       this.tras069 = tras069;
       this.technique = technique;
       this.barcode = barcode;
       this.origProdNo = origProdNo;
       this.raasInitDate = raasInitDate;
       this.raasInitUser = raasInitUser;
       this.firstReleaseDate = firstReleaseDate;
       this.configSet = configSet;
       this.subTitle = subTitle;
       this.backLine = backLine;
       this.noOfSides = noOfSides;
       this.isComplete = isComplete;
       this.editCount = editCount;
       this.explanation = explanation;
       this.merchType = merchType;
       this.merchSize = merchSize;
       this.merchColour = merchColour;
       this.generateSkip = generateSkip;
       this.completeStamp = completeStamp;
       this.completeUser = completeUser;
       this.logModStamp = logModStamp;
       this.logModUser = logModUser;
       this.CLine = CLine;
       this.isLocalFlag = isLocalFlag;
       this.generatedByGridFlag = generatedByGridFlag;
       this.gridNo = gridNo;
       this.isCopyControlled = isCopyControlled;
       this.audioFormat = audioFormat;
       this.imageFormat = imageFormat;
       this.gasFamilyId = gasFamilyId;
       this.catlgCoreId = catlgCoreId;
       this.catlgPfixId = catlgPfixId;
       this.affiliateId = affiliateId;
       this.firstCompleteStamp = firstCompleteStamp;
       this.firstCompleteUser = firstCompleteUser;
       this.gdsCatlgPfixId = gdsCatlgPfixId;
       this.gdsAffiliateId = gdsAffiliateId;
       this.modStamp = modStamp;
       this.modFlag = modFlag;
       this.modUser = modUser;
       this.tras009s = tras009s;
       this.tras003s = tras003s;
       this.tras203s = tras203s;
    }
    
   
    // Property accessors
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="prodNo", column=@Column(name="prod_no", unique=false, nullable=false, insertable=true, updatable=true, length=14) ), 
        @AttributeOverride(name="clientKey", column=@Column(name="client_key", unique=false, nullable=false, insertable=true, updatable=true, length=4) ) } )
    public Tras001Id getId() {
        return this.id;
    }
    
    public void setId(Tras001Id id) {
        this.id = id;
    }

    @ManyToOne(cascade={},
            fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="mono_stereo_key", unique=false, nullable=true, insertable=false, updatable=false), 
        @JoinColumn(name="client_key", unique=false, nullable=true, insertable=false, updatable=false) } )
    public Tras070 getTras070() {
        return this.tras070;
    }
    
    public void setTras070(Tras070 tras070) {
        this.tras070 = tras070;
    }
@ManyToOne(cascade={},
        fetch=FetchType.LAZY)
    
    @JoinColumn(name="region_code_key", unique=false, nullable=true, insertable=true, updatable=true)

    public Tras197 getTras197() {
        return this.tras197;
    }
    
    public void setTras197(Tras197 tras197) {
        this.tras197 = tras197;
    }
@ManyToOne(cascade={},
        fetch=FetchType.LAZY)
    
    @JoinColumns( { 
        @JoinColumn(name="data_source_key", unique=false, nullable=true, insertable=false, updatable=false), 
        @JoinColumn(name="client_key", unique=false, nullable=true, insertable=false, updatable=false) } )

    public Tras095 getTras095() {
        return this.tras095;
    }
    
    public void setTras095(Tras095 tras095) {
        this.tras095 = tras095;
    }
@ManyToOne(cascade={},
        fetch=FetchType.LAZY)
    
    @JoinColumns( { 
        @JoinColumn(name="drm_code_key", unique=false, nullable=true, insertable=false, updatable=false), 
        @JoinColumn(name="client_key", unique=false, nullable=true, insertable=false, updatable=false) } )

    public Tras160 getTras160() {
        return this.tras160;
    }
    
    public void setTras160(Tras160 tras160) {
        this.tras160 = tras160;
    }
@ManyToOne(cascade={},
        fetch=FetchType.LAZY)
    
    @JoinColumns( { 
        @JoinColumn(name="dvd_pictures_tid", unique=false, nullable=true, insertable=false, updatable=false), 
        @JoinColumn(name="client_key", unique=false, nullable=true, insertable=false, updatable=false) } )

    public Tras039 getTras039ByTras001470305864() {
        return this.tras039ByTras001470305864;
    }
    
    public void setTras039ByTras001470305864(Tras039 tras039ByTras001470305864) {
        this.tras039ByTras001470305864 = tras039ByTras001470305864;
    }
@ManyToOne(cascade={},
        fetch=FetchType.LAZY)
    
    @JoinColumn(name="video_format_key", unique=false, nullable=true, insertable=true, updatable=true)

    public Tras198 getTras198() {
        return this.tras198;
    }
    
    public void setTras198(Tras198 tras198) {
        this.tras198 = tras198;
    }
@ManyToOne(cascade={},
        fetch=FetchType.LAZY)
    
    @JoinColumns( { 
        @JoinColumn(name="glob_addit_info_tid", unique=false, nullable=true, insertable=false, updatable=false), 
        @JoinColumn(name="client_key", unique=false, nullable=true, insertable=false, updatable=false) } )

    public Tras039 getTras039ByTras001710306719() {
        return this.tras039ByTras001710306719;
    }
    
    public void setTras039ByTras001710306719(Tras039 tras039ByTras001710306719) {
        this.tras039ByTras001710306719 = tras039ByTras001710306719;
    }
@ManyToOne(cascade={},
        fetch=FetchType.LAZY)
    
    @JoinColumns( { 
        @JoinColumn(name="maint_owner_key", unique=false, nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="client_key", unique=false, nullable=false, insertable=false, updatable=false) } )

    public Tras024 getTras024ByTras001614306377() {
        return this.tras024ByTras001614306377;
    }
    
    public void setTras024ByTras001614306377(Tras024 tras024ByTras001614306377) {
        this.tras024ByTras001614306377 = tras024ByTras001614306377;
    }
@ManyToOne(cascade={},
        fetch=FetchType.LAZY)
    
    @JoinColumns( { 
        @JoinColumn(name="dvd_biographies_tid", unique=false, nullable=true, insertable=false, updatable=false), 
        @JoinColumn(name="client_key", unique=false, nullable=true, insertable=false, updatable=false) } )

    public Tras039 getTras039ByTras001454305807() {
        return this.tras039ByTras001454305807;
    }
    
    public void setTras039ByTras001454305807(Tras039 tras039ByTras001454305807) {
        this.tras039ByTras001454305807 = tras039ByTras001454305807;
    }
@ManyToOne(cascade={},
        fetch=FetchType.LAZY)
    
    @JoinColumns( { 
        @JoinColumn(name="prod_vers_no", unique=false, nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="client_key", unique=false, nullable=false, insertable=false, updatable=false) } )

    public Tras002 getTras002() {
        return this.tras002;
    }
    
    public void setTras002(Tras002 tras002) {
        this.tras002 = tras002;
    }
@ManyToOne(cascade={},
        fetch=FetchType.LAZY)
    
    @JoinColumns( { 
        @JoinColumn(name="dvd_info_tid", unique=false, nullable=true, insertable=false, updatable=false), 
        @JoinColumn(name="client_key", unique=false, nullable=true, insertable=false, updatable=false) } )

    public Tras039 getTras039ByTras001422305693() {
        return this.tras039ByTras001422305693;
    }
    
    public void setTras039ByTras001422305693(Tras039 tras039ByTras001422305693) {
        this.tras039ByTras001422305693 = tras039ByTras001422305693;
    }
@ManyToOne(cascade={},
        fetch=FetchType.LAZY)
    
    @JoinColumn(name="gds_catlg_core_id", unique=false, nullable=true, insertable=true, updatable=true)

    public Tras207 getTras207() {
        return this.tras207;
    }
    
    public void setTras207(Tras207 tras207) {
        this.tras207 = tras207;
    }
@ManyToOne(cascade={},
        fetch=FetchType.LAZY)
    
    @JoinColumn(name="client_key", unique=false, nullable=false, insertable=false, updatable=false)

    public Tras062 getTras062() {
        return this.tras062;
    }
    
    public void setTras062(Tras062 tras062) {
        this.tras062 = tras062;
    }
@ManyToOne(cascade={},
        fetch=FetchType.LAZY)
    
    @JoinColumns( { 
        @JoinColumn(name="noise_red_key", unique=false, nullable=true, insertable=false, updatable=false), 
        @JoinColumn(name="client_key", unique=false, nullable=true, insertable=false, updatable=false) } )

    public Tras071 getTras071() {
        return this.tras071;
    }
    
    public void setTras071(Tras071 tras071) {
        this.tras071 = tras071;
    }
@ManyToOne(cascade={},
        fetch=FetchType.LAZY)
    
    @JoinColumns( { 
        @JoinColumn(name="dvd_software_tid", unique=false, nullable=true, insertable=false, updatable=false), 
        @JoinColumn(name="client_key", unique=false, nullable=true, insertable=false, updatable=false) } )

    public Tras039 getTras039ByTras001486305921() {
        return this.tras039ByTras001486305921;
    }
    
    public void setTras039ByTras001486305921(Tras039 tras039ByTras001486305921) {
        this.tras039ByTras001486305921 = tras039ByTras001486305921;
    }
@ManyToOne(cascade={},
        fetch=FetchType.LAZY)
    
    @JoinColumns( { 
        @JoinColumn(name="codec_key", unique=false, nullable=true, insertable=false, updatable=false), 
        @JoinColumn(name="client_key", unique=false, nullable=true, insertable=false, updatable=false) } )

    public Tras159 getTras159() {
        return this.tras159;
    }
    
    public void setTras159(Tras159 tras159) {
        this.tras159 = tras159;
    }
@ManyToOne(cascade={},
        fetch=FetchType.LAZY)
    
    @JoinColumn(name="dvd_type_key", unique=false, nullable=true, insertable=true, updatable=true)

    public Tras196 getTras196() {
        return this.tras196;
    }
    
    public void setTras196(Tras196 tras196) {
        this.tras196 = tras196;
    }
@ManyToOne(cascade={},
        fetch=FetchType.LAZY)
    
    @JoinColumns( { 
        @JoinColumn(name="dvd_weblinks_tid", unique=false, nullable=true, insertable=false, updatable=false), 
        @JoinColumn(name="client_key", unique=false, nullable=true, insertable=false, updatable=false) } )

    public Tras039 getTras039ByTras001438305750() {
        return this.tras039ByTras001438305750;
    }
    
    public void setTras039ByTras001438305750(Tras039 tras039ByTras001438305750) {
        this.tras039ByTras001438305750 = tras039ByTras001438305750;
    }
@ManyToOne(cascade={},
        fetch=FetchType.LAZY)
    
    @JoinColumns( { 
        @JoinColumn(name="raas_init_key", unique=false, nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="client_key", unique=false, nullable=false, insertable=false, updatable=false) } )

    public Tras024 getTras024ByTras001582306263() {
        return this.tras024ByTras001582306263;
    }
    
    public void setTras024ByTras001582306263(Tras024 tras024ByTras001582306263) {
        this.tras024ByTras001582306263 = tras024ByTras001582306263;
    }
@ManyToOne(cascade={},
        fetch=FetchType.LAZY)
    
    @JoinColumns( { 
        @JoinColumn(name="config_key", unique=false, nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="client_key", unique=false, nullable=false, insertable=false, updatable=false) } )

    public Tras025 getTras025() {
        return this.tras025;
    }
    
    public void setTras025(Tras025 tras025) {
        this.tras025 = tras025;
    }
@ManyToOne(cascade={},
        fetch=FetchType.LAZY)
    
    @JoinColumns( { 
        @JoinColumn(name="spars_code_key", unique=false, nullable=true, insertable=false, updatable=false), 
        @JoinColumn(name="client_key", unique=false, nullable=true, insertable=false, updatable=false) } )

    public Tras069 getTras069() {
        return this.tras069;
    }
    
    public void setTras069(Tras069 tras069) {
        this.tras069 = tras069;
    }
    
    @Column(name="technique", unique=false, nullable=true, insertable=true, updatable=true, length=250)
    public String getTechnique() {
        return this.technique;
    }
    
    public void setTechnique(String technique) {
        this.technique = technique;
    }
    
    @Column(name="barcode", unique=false, nullable=true, insertable=true, updatable=true, length=13)
    public String getBarcode() {
        return this.barcode;
    }
    
    public void setBarcode(String barcode) {
        this.barcode = barcode;
    }
    
    @Column(name="orig_prod_no", unique=false, nullable=true, insertable=true, updatable=true, length=15)
    public String getOrigProdNo() {
        return this.origProdNo;
    }
    
    public void setOrigProdNo(String origProdNo) {
        this.origProdNo = origProdNo;
    }
    
    @Column(name="raas_init_date", unique=false, nullable=false, insertable=true, updatable=true, length=8)
    public String getRaasInitDate() {
        return this.raasInitDate;
    }
    
    public void setRaasInitDate(String raasInitDate) {
        this.raasInitDate = raasInitDate;
    }
    
    @Column(name="raas_init_user", unique=false, nullable=true, insertable=true, updatable=true, length=8)
    public String getRaasInitUser() {
        return this.raasInitUser;
    }
    
    public void setRaasInitUser(String raasInitUser) {
        this.raasInitUser = raasInitUser;
    }
    
    @Column(name="first_release_date", unique=false, nullable=true, insertable=true, updatable=true, length=8)
    public String getFirstReleaseDate() {
        return this.firstReleaseDate;
    }
    
    public void setFirstReleaseDate(String firstReleaseDate) {
        this.firstReleaseDate = firstReleaseDate;
    }
    
    @Column(name="config_set", unique=false, nullable=false, insertable=true, updatable=true)
    public short getConfigSet() {
        return this.configSet;
    }
    
    public void setConfigSet(short configSet) {
        this.configSet = configSet;
    }
    
    @Column(name="sub_title", unique=false, nullable=true, insertable=true, updatable=true, length=250)
    public String getSubTitle() {
        return this.subTitle;
    }
    
    public void setSubTitle(String subTitle) {
        this.subTitle = subTitle;
    }
    
    @Column(name="back_line", unique=false, nullable=true, insertable=true, updatable=true, length=250)
    public String getBackLine() {
        return this.backLine;
    }
    
    public void setBackLine(String backLine) {
        this.backLine = backLine;
    }
    
    @Column(name="no_of_sides", unique=false, nullable=true, insertable=true, updatable=true)
    public Short getNoOfSides() {
        return this.noOfSides;
    }
    
    public void setNoOfSides(Short noOfSides) {
        this.noOfSides = noOfSides;
    }
    
    @Column(name="is_complete", unique=false, nullable=false, insertable=true, updatable=true, length=1)
    public char getIsComplete() {
        return this.isComplete;
    }
    
    public void setIsComplete(char isComplete) {
        this.isComplete = isComplete;
    }
    
    @Column(name="edit_count", unique=false, nullable=false, insertable=true, updatable=true)
    public short getEditCount() {
        return this.editCount;
    }
    
    public void setEditCount(short editCount) {
        this.editCount = editCount;
    }
    
    @Column(name="explanation", unique=false, nullable=true, insertable=true, updatable=true, length=250)
    public String getExplanation() {
        return this.explanation;
    }
    
    public void setExplanation(String explanation) {
        this.explanation = explanation;
    }
    
    @Column(name="merch_type", unique=false, nullable=true, insertable=true, updatable=true, length=250)
    public String getMerchType() {
        return this.merchType;
    }
    
    public void setMerchType(String merchType) {
        this.merchType = merchType;
    }
    
    @Column(name="merch_size", unique=false, nullable=true, insertable=true, updatable=true, length=50)
    public String getMerchSize() {
        return this.merchSize;
    }
    
    public void setMerchSize(String merchSize) {
        this.merchSize = merchSize;
    }
    
    @Column(name="merch_colour", unique=false, nullable=true, insertable=true, updatable=true, length=50)
    public String getMerchColour() {
        return this.merchColour;
    }
    
    public void setMerchColour(String merchColour) {
        this.merchColour = merchColour;
    }
    
    @Column(name="generate_skip", unique=false, nullable=true, insertable=true, updatable=true)
    public Short getGenerateSkip() {
        return this.generateSkip;
    }
    
    public void setGenerateSkip(Short generateSkip) {
        this.generateSkip = generateSkip;
    }
    
    @Column(name="complete_stamp", unique=false, nullable=true, insertable=true, updatable=true, length=23)
    public Date getCompleteStamp() {
        return this.completeStamp;
    }
    
    public void setCompleteStamp(Date completeStamp) {
        this.completeStamp = completeStamp;
    }
    
    @Column(name="complete_user", unique=false, nullable=true, insertable=true, updatable=true, length=8)
    public String getCompleteUser() {
        return this.completeUser;
    }
    
    public void setCompleteUser(String completeUser) {
        this.completeUser = completeUser;
    }
    
    @Column(name="log_mod_stamp", unique=false, nullable=true, insertable=true, updatable=true, length=23)
    public Date getLogModStamp() {
        return this.logModStamp;
    }
    
    public void setLogModStamp(Date logModStamp) {
        this.logModStamp = logModStamp;
    }
    
    @Column(name="log_mod_user", unique=false, nullable=true, insertable=true, updatable=true, length=8)
    public String getLogModUser() {
        return this.logModUser;
    }
    
    public void setLogModUser(String logModUser) {
        this.logModUser = logModUser;
    }
    
    @Column(name="c_line", unique=false, nullable=true, insertable=true, updatable=true, length=250)
    public String getCLine() {
        return this.CLine;
    }
    
    public void setCLine(String CLine) {
        this.CLine = CLine;
    }
    
    @Column(name="is_local_flag", unique=false, nullable=true, insertable=true, updatable=true, length=1)
    public Character getIsLocalFlag() {
        return this.isLocalFlag;
    }
    
    public void setIsLocalFlag(Character isLocalFlag) {
        this.isLocalFlag = isLocalFlag;
    }
    
    @Column(name="generated_by_grid_flag", unique=false, nullable=true, insertable=true, updatable=true, length=1)
    public Character getGeneratedByGridFlag() {
        return this.generatedByGridFlag;
    }
    
    public void setGeneratedByGridFlag(Character generatedByGridFlag) {
        this.generatedByGridFlag = generatedByGridFlag;
    }
    
    @Column(name="grid_no", unique=false, nullable=true, insertable=true, updatable=true, length=18)
    public String getGridNo() {
        return this.gridNo;
    }
    
    public void setGridNo(String gridNo) {
        this.gridNo = gridNo;
    }
    
    @Column(name="is_copy_controlled", unique=false, nullable=true, insertable=true, updatable=true, length=1)
    public Character getIsCopyControlled() {
        return this.isCopyControlled;
    }
    
    public void setIsCopyControlled(Character isCopyControlled) {
        this.isCopyControlled = isCopyControlled;
    }
    
    @Column(name="audio_format", unique=false, nullable=true, insertable=true, updatable=true, length=250)
    public String getAudioFormat() {
        return this.audioFormat;
    }
    
    public void setAudioFormat(String audioFormat) {
        this.audioFormat = audioFormat;
    }
    
    @Column(name="image_format", unique=false, nullable=true, insertable=true, updatable=true, length=250)
    public String getImageFormat() {
        return this.imageFormat;
    }
    
    public void setImageFormat(String imageFormat) {
        this.imageFormat = imageFormat;
    }
    
    @Column(name="gas_family_id", unique=false, nullable=true, insertable=true, updatable=true, length=6)
    public String getGasFamilyId() {
        return this.gasFamilyId;
    }
    
    public void setGasFamilyId(String gasFamilyId) {
        this.gasFamilyId = gasFamilyId;
    }
    
    @Column(name="catlg_core_id", unique=false, nullable=true, insertable=true, updatable=true, length=6)
    public String getCatlgCoreId() {
        return this.catlgCoreId;
    }
    
    public void setCatlgCoreId(String catlgCoreId) {
        this.catlgCoreId = catlgCoreId;
    }
    
    @Column(name="catlg_pfix_id", unique=false, nullable=true, insertable=true, updatable=true, length=6)
    public String getCatlgPfixId() {
        return this.catlgPfixId;
    }
    
    public void setCatlgPfixId(String catlgPfixId) {
        this.catlgPfixId = catlgPfixId;
    }
    
    @Column(name="affiliate_id", unique=false, nullable=true, insertable=true, updatable=true, length=4)
    public String getAffiliateId() {
        return this.affiliateId;
    }
    
    public void setAffiliateId(String affiliateId) {
        this.affiliateId = affiliateId;
    }
    
    @Column(name="first_complete_stamp", unique=false, nullable=true, insertable=true, updatable=true, length=23)
    public Date getFirstCompleteStamp() {
        return this.firstCompleteStamp;
    }
    
    public void setFirstCompleteStamp(Date firstCompleteStamp) {
        this.firstCompleteStamp = firstCompleteStamp;
    }
    
    @Column(name="first_complete_user", unique=false, nullable=true, insertable=true, updatable=true, length=8)
    public String getFirstCompleteUser() {
        return this.firstCompleteUser;
    }
    
    public void setFirstCompleteUser(String firstCompleteUser) {
        this.firstCompleteUser = firstCompleteUser;
    }
    
    @Column(name="gds_catlg_pfix_id", unique=false, nullable=true, insertable=true, updatable=true, length=6)
    public String getGdsCatlgPfixId() {
        return this.gdsCatlgPfixId;
    }
    
    public void setGdsCatlgPfixId(String gdsCatlgPfixId) {
        this.gdsCatlgPfixId = gdsCatlgPfixId;
    }
    
    @Column(name="gds_affiliate_id", unique=false, nullable=true, insertable=true, updatable=true, length=4)
    public String getGdsAffiliateId() {
        return this.gdsAffiliateId;
    }
    
    public void setGdsAffiliateId(String gdsAffiliateId) {
        this.gdsAffiliateId = gdsAffiliateId;
    }
    
    @Column(name="mod_stamp", unique=false, nullable=false, insertable=true, updatable=true, length=23)
    public Date getModStamp() {
        return this.modStamp;
    }
    
    public void setModStamp(Date modStamp) {
        this.modStamp = modStamp;
    }
    
    @Column(name="mod_flag", unique=false, nullable=false, insertable=true, updatable=true, length=1)
    public char getModFlag() {
        return this.modFlag;
    }
    
    public void setModFlag(char modFlag) {
        this.modFlag = modFlag;
    }
    
    @Column(name="mod_user", unique=false, nullable=false, insertable=true, updatable=true, length=8)
    public String getModUser() {
        return this.modUser;
    }
    
    public void setModUser(String modUser) {
        this.modUser = modUser;
    }
    @OneToMany(cascade={}, fetch=FetchType.LAZY, mappedBy="tras001")
    @JoinColumns( { 
        @JoinColumn(name="client_key"    ), 
        @JoinColumn(name="prod_no"    ) } )
    public Set<Tras009> getTras009s() {
        return this.tras009s;
    }
    
    public void setTras009s(Set<Tras009> tras009s) {
        this.tras009s = tras009s;
    }
    @OneToMany(cascade={}, fetch=FetchType.LAZY, mappedBy="tras001")
    @JoinColumns( { 
        @JoinColumn(name="prod_no"    ), 
        @JoinColumn(name="client_key"    ) } )
    public Set<Tras003> getTras003s() {
        return this.tras003s;
    }
    
    public void setTras003s(Set<Tras003> tras003s) {
        this.tras003s = tras003s;
    }
    @OneToMany(cascade={}, fetch=FetchType.LAZY, mappedBy="tras001")
    @JoinColumns( { 
        @JoinColumn(name="prod_no"    ), 
        @JoinColumn(name="client_key"    ) } )
    public Set<Tras203> getTras203s() {
        return this.tras203s;
    }
    
    public void setTras203s(Set<Tras203> tras203s) {
        this.tras203s = tras203s;
    }

    /**
     * toString
     * @return String
     */
     public String toString() {
	  StringBuffer buffer = new StringBuffer();

      buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
      buffer.append("technique").append("='").append(getTechnique()).append("' ");			
      buffer.append("barcode").append("='").append(getBarcode()).append("' ");			
      buffer.append("origProdNo").append("='").append(getOrigProdNo()).append("' ");			
      buffer.append("raasInitDate").append("='").append(getRaasInitDate()).append("' ");			
      buffer.append("raasInitUser").append("='").append(getRaasInitUser()).append("' ");			
      buffer.append("firstReleaseDate").append("='").append(getFirstReleaseDate()).append("' ");			
      buffer.append("configSet").append("='").append(getConfigSet()).append("' ");			
      buffer.append("subTitle").append("='").append(getSubTitle()).append("' ");			
      buffer.append("backLine").append("='").append(getBackLine()).append("' ");			
      buffer.append("noOfSides").append("='").append(getNoOfSides()).append("' ");			
      buffer.append("isComplete").append("='").append(getIsComplete()).append("' ");			
      buffer.append("editCount").append("='").append(getEditCount()).append("' ");			
      buffer.append("explanation").append("='").append(getExplanation()).append("' ");			
      buffer.append("merchType").append("='").append(getMerchType()).append("' ");			
      buffer.append("merchSize").append("='").append(getMerchSize()).append("' ");			
      buffer.append("merchColour").append("='").append(getMerchColour()).append("' ");			
      buffer.append("generateSkip").append("='").append(getGenerateSkip()).append("' ");			
      buffer.append("completeStamp").append("='").append(getCompleteStamp()).append("' ");			
      buffer.append("completeUser").append("='").append(getCompleteUser()).append("' ");			
      buffer.append("logModStamp").append("='").append(getLogModStamp()).append("' ");			
      buffer.append("logModUser").append("='").append(getLogModUser()).append("' ");			
      buffer.append("CLine").append("='").append(getCLine()).append("' ");			
      buffer.append("isLocalFlag").append("='").append(getIsLocalFlag()).append("' ");			
      buffer.append("generatedByGridFlag").append("='").append(getGeneratedByGridFlag()).append("' ");			
      buffer.append("gridNo").append("='").append(getGridNo()).append("' ");			
      buffer.append("isCopyControlled").append("='").append(getIsCopyControlled()).append("' ");			
      buffer.append("audioFormat").append("='").append(getAudioFormat()).append("' ");			
      buffer.append("imageFormat").append("='").append(getImageFormat()).append("' ");			
      buffer.append("gasFamilyId").append("='").append(getGasFamilyId()).append("' ");			
      buffer.append("catlgCoreId").append("='").append(getCatlgCoreId()).append("' ");			
      buffer.append("catlgPfixId").append("='").append(getCatlgPfixId()).append("' ");			
      buffer.append("affiliateId").append("='").append(getAffiliateId()).append("' ");			
      buffer.append("firstCompleteStamp").append("='").append(getFirstCompleteStamp()).append("' ");			
      buffer.append("firstCompleteUser").append("='").append(getFirstCompleteUser()).append("' ");			
      buffer.append("gdsCatlgPfixId").append("='").append(getGdsCatlgPfixId()).append("' ");			
      buffer.append("gdsAffiliateId").append("='").append(getGdsAffiliateId()).append("' ");			
      buffer.append("modStamp").append("='").append(getModStamp()).append("' ");			
      buffer.append("modFlag").append("='").append(getModFlag()).append("' ");			
      buffer.append("modUser").append("='").append(getModUser()).append("' ");			
      buffer.append("]");
      
      return buffer.toString();
     }

   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof Tras001) ) return false;
		 Tras001 castOther = ( Tras001 ) other; 
         
		 return ( (this.getTechnique()==castOther.getTechnique()) || ( this.getTechnique()!=null && castOther.getTechnique()!=null && this.getTechnique().equals(castOther.getTechnique()) ) )
 && ( (this.getBarcode()==castOther.getBarcode()) || ( this.getBarcode()!=null && castOther.getBarcode()!=null && this.getBarcode().equals(castOther.getBarcode()) ) )
 && ( (this.getOrigProdNo()==castOther.getOrigProdNo()) || ( this.getOrigProdNo()!=null && castOther.getOrigProdNo()!=null && this.getOrigProdNo().equals(castOther.getOrigProdNo()) ) )
 && ( (this.getRaasInitDate()==castOther.getRaasInitDate()) || ( this.getRaasInitDate()!=null && castOther.getRaasInitDate()!=null && this.getRaasInitDate().equals(castOther.getRaasInitDate()) ) )
 && ( (this.getRaasInitUser()==castOther.getRaasInitUser()) || ( this.getRaasInitUser()!=null && castOther.getRaasInitUser()!=null && this.getRaasInitUser().equals(castOther.getRaasInitUser()) ) )
 && ( (this.getFirstReleaseDate()==castOther.getFirstReleaseDate()) || ( this.getFirstReleaseDate()!=null && castOther.getFirstReleaseDate()!=null && this.getFirstReleaseDate().equals(castOther.getFirstReleaseDate()) ) )
 && (this.getConfigSet()==castOther.getConfigSet())
 && ( (this.getSubTitle()==castOther.getSubTitle()) || ( this.getSubTitle()!=null && castOther.getSubTitle()!=null && this.getSubTitle().equals(castOther.getSubTitle()) ) )
 && ( (this.getBackLine()==castOther.getBackLine()) || ( this.getBackLine()!=null && castOther.getBackLine()!=null && this.getBackLine().equals(castOther.getBackLine()) ) )
 && ( (this.getNoOfSides()==castOther.getNoOfSides()) || ( this.getNoOfSides()!=null && castOther.getNoOfSides()!=null && this.getNoOfSides().equals(castOther.getNoOfSides()) ) )
 && (this.getIsComplete()==castOther.getIsComplete())
 && (this.getEditCount()==castOther.getEditCount())
 && ( (this.getExplanation()==castOther.getExplanation()) || ( this.getExplanation()!=null && castOther.getExplanation()!=null && this.getExplanation().equals(castOther.getExplanation()) ) )
 && ( (this.getMerchType()==castOther.getMerchType()) || ( this.getMerchType()!=null && castOther.getMerchType()!=null && this.getMerchType().equals(castOther.getMerchType()) ) )
 && ( (this.getMerchSize()==castOther.getMerchSize()) || ( this.getMerchSize()!=null && castOther.getMerchSize()!=null && this.getMerchSize().equals(castOther.getMerchSize()) ) )
 && ( (this.getMerchColour()==castOther.getMerchColour()) || ( this.getMerchColour()!=null && castOther.getMerchColour()!=null && this.getMerchColour().equals(castOther.getMerchColour()) ) )
 && ( (this.getGenerateSkip()==castOther.getGenerateSkip()) || ( this.getGenerateSkip()!=null && castOther.getGenerateSkip()!=null && this.getGenerateSkip().equals(castOther.getGenerateSkip()) ) )
 && ( (this.getCompleteStamp()==castOther.getCompleteStamp()) || ( this.getCompleteStamp()!=null && castOther.getCompleteStamp()!=null && this.getCompleteStamp().equals(castOther.getCompleteStamp()) ) )
 && ( (this.getCompleteUser()==castOther.getCompleteUser()) || ( this.getCompleteUser()!=null && castOther.getCompleteUser()!=null && this.getCompleteUser().equals(castOther.getCompleteUser()) ) )
 && ( (this.getLogModStamp()==castOther.getLogModStamp()) || ( this.getLogModStamp()!=null && castOther.getLogModStamp()!=null && this.getLogModStamp().equals(castOther.getLogModStamp()) ) )
 && ( (this.getLogModUser()==castOther.getLogModUser()) || ( this.getLogModUser()!=null && castOther.getLogModUser()!=null && this.getLogModUser().equals(castOther.getLogModUser()) ) )
 && ( (this.getCLine()==castOther.getCLine()) || ( this.getCLine()!=null && castOther.getCLine()!=null && this.getCLine().equals(castOther.getCLine()) ) )
 && ( (this.getIsLocalFlag()==castOther.getIsLocalFlag()) || ( this.getIsLocalFlag()!=null && castOther.getIsLocalFlag()!=null && this.getIsLocalFlag().equals(castOther.getIsLocalFlag()) ) )
 && ( (this.getGeneratedByGridFlag()==castOther.getGeneratedByGridFlag()) || ( this.getGeneratedByGridFlag()!=null && castOther.getGeneratedByGridFlag()!=null && this.getGeneratedByGridFlag().equals(castOther.getGeneratedByGridFlag()) ) )
 && ( (this.getGridNo()==castOther.getGridNo()) || ( this.getGridNo()!=null && castOther.getGridNo()!=null && this.getGridNo().equals(castOther.getGridNo()) ) )
 && ( (this.getIsCopyControlled()==castOther.getIsCopyControlled()) || ( this.getIsCopyControlled()!=null && castOther.getIsCopyControlled()!=null && this.getIsCopyControlled().equals(castOther.getIsCopyControlled()) ) )
 && ( (this.getAudioFormat()==castOther.getAudioFormat()) || ( this.getAudioFormat()!=null && castOther.getAudioFormat()!=null && this.getAudioFormat().equals(castOther.getAudioFormat()) ) )
 && ( (this.getImageFormat()==castOther.getImageFormat()) || ( this.getImageFormat()!=null && castOther.getImageFormat()!=null && this.getImageFormat().equals(castOther.getImageFormat()) ) )
 && ( (this.getGasFamilyId()==castOther.getGasFamilyId()) || ( this.getGasFamilyId()!=null && castOther.getGasFamilyId()!=null && this.getGasFamilyId().equals(castOther.getGasFamilyId()) ) )
 && ( (this.getCatlgCoreId()==castOther.getCatlgCoreId()) || ( this.getCatlgCoreId()!=null && castOther.getCatlgCoreId()!=null && this.getCatlgCoreId().equals(castOther.getCatlgCoreId()) ) )
 && ( (this.getCatlgPfixId()==castOther.getCatlgPfixId()) || ( this.getCatlgPfixId()!=null && castOther.getCatlgPfixId()!=null && this.getCatlgPfixId().equals(castOther.getCatlgPfixId()) ) )
 && ( (this.getAffiliateId()==castOther.getAffiliateId()) || ( this.getAffiliateId()!=null && castOther.getAffiliateId()!=null && this.getAffiliateId().equals(castOther.getAffiliateId()) ) )
 && ( (this.getFirstCompleteStamp()==castOther.getFirstCompleteStamp()) || ( this.getFirstCompleteStamp()!=null && castOther.getFirstCompleteStamp()!=null && this.getFirstCompleteStamp().equals(castOther.getFirstCompleteStamp()) ) )
 && ( (this.getFirstCompleteUser()==castOther.getFirstCompleteUser()) || ( this.getFirstCompleteUser()!=null && castOther.getFirstCompleteUser()!=null && this.getFirstCompleteUser().equals(castOther.getFirstCompleteUser()) ) )
 && ( (this.getGdsCatlgPfixId()==castOther.getGdsCatlgPfixId()) || ( this.getGdsCatlgPfixId()!=null && castOther.getGdsCatlgPfixId()!=null && this.getGdsCatlgPfixId().equals(castOther.getGdsCatlgPfixId()) ) )
 && ( (this.getGdsAffiliateId()==castOther.getGdsAffiliateId()) || ( this.getGdsAffiliateId()!=null && castOther.getGdsAffiliateId()!=null && this.getGdsAffiliateId().equals(castOther.getGdsAffiliateId()) ) )
 && ( (this.getModStamp()==castOther.getModStamp()) || ( this.getModStamp()!=null && castOther.getModStamp()!=null && this.getModStamp().equals(castOther.getModStamp()) ) )
 && (this.getModFlag()==castOther.getModFlag())
 && ( (this.getModUser()==castOther.getModUser()) || ( this.getModUser()!=null && castOther.getModUser()!=null && this.getModUser().equals(castOther.getModUser()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         
         result = 37 * result + ( getTechnique() == null ? 0 : this.getTechnique().hashCode() );
         result = 37 * result + ( getBarcode() == null ? 0 : this.getBarcode().hashCode() );
         result = 37 * result + ( getOrigProdNo() == null ? 0 : this.getOrigProdNo().hashCode() );
         result = 37 * result + ( getRaasInitDate() == null ? 0 : this.getRaasInitDate().hashCode() );
         result = 37 * result + ( getRaasInitUser() == null ? 0 : this.getRaasInitUser().hashCode() );
         result = 37 * result + ( getFirstReleaseDate() == null ? 0 : this.getFirstReleaseDate().hashCode() );
         result = 37 * result + this.getConfigSet();
         result = 37 * result + ( getSubTitle() == null ? 0 : this.getSubTitle().hashCode() );
         result = 37 * result + ( getBackLine() == null ? 0 : this.getBackLine().hashCode() );
         result = 37 * result + ( getNoOfSides() == null ? 0 : this.getNoOfSides().hashCode() );
         result = 37 * result + this.getIsComplete();
         result = 37 * result + this.getEditCount();
         result = 37 * result + ( getExplanation() == null ? 0 : this.getExplanation().hashCode() );
         result = 37 * result + ( getMerchType() == null ? 0 : this.getMerchType().hashCode() );
         result = 37 * result + ( getMerchSize() == null ? 0 : this.getMerchSize().hashCode() );
         result = 37 * result + ( getMerchColour() == null ? 0 : this.getMerchColour().hashCode() );
         result = 37 * result + ( getGenerateSkip() == null ? 0 : this.getGenerateSkip().hashCode() );
         result = 37 * result + ( getCompleteStamp() == null ? 0 : this.getCompleteStamp().hashCode() );
         result = 37 * result + ( getCompleteUser() == null ? 0 : this.getCompleteUser().hashCode() );
         result = 37 * result + ( getLogModStamp() == null ? 0 : this.getLogModStamp().hashCode() );
         result = 37 * result + ( getLogModUser() == null ? 0 : this.getLogModUser().hashCode() );
         result = 37 * result + ( getCLine() == null ? 0 : this.getCLine().hashCode() );
         result = 37 * result + ( getIsLocalFlag() == null ? 0 : this.getIsLocalFlag().hashCode() );
         result = 37 * result + ( getGeneratedByGridFlag() == null ? 0 : this.getGeneratedByGridFlag().hashCode() );
         result = 37 * result + ( getGridNo() == null ? 0 : this.getGridNo().hashCode() );
         result = 37 * result + ( getIsCopyControlled() == null ? 0 : this.getIsCopyControlled().hashCode() );
         result = 37 * result + ( getAudioFormat() == null ? 0 : this.getAudioFormat().hashCode() );
         result = 37 * result + ( getImageFormat() == null ? 0 : this.getImageFormat().hashCode() );
         result = 37 * result + ( getGasFamilyId() == null ? 0 : this.getGasFamilyId().hashCode() );
         result = 37 * result + ( getCatlgCoreId() == null ? 0 : this.getCatlgCoreId().hashCode() );
         result = 37 * result + ( getCatlgPfixId() == null ? 0 : this.getCatlgPfixId().hashCode() );
         result = 37 * result + ( getAffiliateId() == null ? 0 : this.getAffiliateId().hashCode() );
         result = 37 * result + ( getFirstCompleteStamp() == null ? 0 : this.getFirstCompleteStamp().hashCode() );
         result = 37 * result + ( getFirstCompleteUser() == null ? 0 : this.getFirstCompleteUser().hashCode() );
         result = 37 * result + ( getGdsCatlgPfixId() == null ? 0 : this.getGdsCatlgPfixId().hashCode() );
         result = 37 * result + ( getGdsAffiliateId() == null ? 0 : this.getGdsAffiliateId().hashCode() );
         result = 37 * result + ( getModStamp() == null ? 0 : this.getModStamp().hashCode() );
         result = 37 * result + this.getModFlag();
         result = 37 * result + ( getModUser() == null ? 0 : this.getModUser().hashCode() );
         
         
         
         return result;
   }   


}


