/*
 * $Header:  $
 * $Revision:  $
 * $Date:  $
 * 
 * ============================================================================
 *          The C24 IO Deployed Component Software License, Version 1.1
 * ============================================================================
 * 
 * Copyright (c) 2000-2004 Century 24 Solutions Ltd. All  Rights Reserved.
 * 
 * Century 24 Solutions Limited ("C24") authorizes redistribution
 * and use of this software in source and binary forms, with or without
 * modification, for non-resale purposes only, provided that the
 * following conditions are met:
 * 
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 
 * 2. Redistribution in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the distribution.
 * 
 * 3. The names "Integration Objects" and "C24 IO" must not be used to
 *    endorse or promote products derived from this software without prior
 *    written permission. For written permission, please contact io@c24.biz.
 * 
 * This software is provided "AS IS," without a warranty of any kind. ALL
 * EXPRESS OR IMPLIED CONDITIONS, REPRESENTATIONS AND WARRANTIES, INCLUDING
 * ANY IMPLIED WARRANTY OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE
 * OR NON-INFRINGEMENT, ARE HEREBY EXCLUDED. CENTURY 24 SOLUTIONS AND ITS
 * LICENSORS SHALL NOT BE LIABLE FOR ANY DAMAGES OR LIABILITIES SUFFERED BY
 * LICENSEE AS A RESULT OF OR RELATING TO USE, MODIFICATION OR DISTRIBUTION
 * OF THE SOFTWARE OR ITS DERIVATIVES. IN NO EVENT WILL CENTURY 24 SOLUTIONS
 * OR ITS LICENSORS BE LIABLE FOR ANY LOST REVENUE, PROFIT OR DATA, OR FOR DIRECT,
 * INDIRECT, SPECIAL, CONSEQUENTIAL, INCIDENTAL OR PUNITIVE DAMAGES, HOWEVER
 * CAUSED AND REGARDLESS OF THE THEORY OF LIABILITY, ARISING OUT OF THE USE OF
 * OR INABILITY TO USE SOFTWARE, EVEN IF CENTURY 24 SOLUTIONS HAS BEEN ADVISED
 * OF THE POSSIBILITY OF SUCH DAMAGES.
 * 
 * You acknowledge that the Software is not designed, licensed or intended for
 * use in the design, construction, operation or maintenance of any nuclear
 * facility.
 * 
 * For information concerning C24 IO and other C24 products and services, contact
 * us at info@c24.biz or visit www.c24.biz
 * 
 * Auto-Generated by Century 24 Integration Objects.
 */

package biz.c24.io.csv;


/**
 * An object with get / set methods specific to its type.
 * @author C24 Integration Objects&#174;
 * @see biz.c24.io.csv.CSVFileClass
 **/
public class CSVFile extends biz.c24.io.api.data.ComplexDataObject 
{
    private biz.c24.io.csv.Record[] record;

    /**
     * Constructs a new instance defined by the default element.
     **/
    public CSVFile()
    {
        super(new biz.c24.io.api.data.Element("CSVFile", 1, 1, biz.c24.io.csv.CSVFileClass.getInstance(), biz.c24.io.csv.CSVDataDataModel.getInstance()));
    }

    /**
     * Constructs a new instance defined by the specified element.
     * @param definingElementDecl The element which defines the object.
     **/
    public CSVFile(biz.c24.io.api.data.Element definingElementDecl)
    {
        super(definingElementDecl);
    }

    /**
     * Constructs a new instance defined by the specified element and type.
     * @param definingElementDecl The element which defines the object.
     * @param type The type which defines the object.
     **/
    public CSVFile(biz.c24.io.api.data.Element definingElementDecl, biz.c24.io.api.data.ComplexDataType type)
    {
        super(definingElementDecl, type);
    }

    /**
     * Constructs a new instance cloned from the specified object.
     * @param clone The object to be cloned.
     **/
    public CSVFile(biz.c24.io.csv.CSVFile clone)
    {
        super(clone);
    }

    /**
     * Adds <code>value</code> as an element called <code>name</code>.<p>
     * The legal value(s) for <code>name</code> are defined in {@link #getElement}.
     **/
    public void addElement(java.lang.String name, java.lang.Object value)
    {
        name = makeSubstitution(name, -1);
        if (name.equals("Record"))
            addRecord((biz.c24.io.csv.Record) value);
        else
            super.addElement(name, value);
    }

    /**
     * Adds a Record (0..*).
     * @param value The new Record.
     **/
    public void addRecord(biz.c24.io.csv.Record value)
    {
        if (value == null)
            throw new java.lang.NullPointerException();
        biz.c24.io.csv.Record[] temp = this.record;
        this.record = new biz.c24.io.csv.Record[temp == null ? 1 : (temp.length+1)];
        if (temp != null)
            java.lang.System.arraycopy(temp, 0, this.record, 0, temp.length);
        this.record[this.record.length-1] = value;
        ((biz.c24.io.api.data.ComplexDataObject) value).setParent(this);
    }

    public java.lang.Object clone()
    {
        return new biz.c24.io.csv.CSVFile(this);
    }

    /**
     * Creates, adds and returns a new Record (0..*).
     * @return The new value.
     **/
    public biz.c24.io.csv.Record createRecord()
    {
        biz.c24.io.csv.Record obj = (biz.c24.io.csv.Record) getElementDecl("Record").createObject();
        addRecord(obj);
        return obj;
    }

    public boolean equals(java.lang.Object obj)
    {
        return super.equals(obj);
    }

    /**
     * Returns the element called <code>name</code> at <code>index</code>.<p>
     * The legal value(s) for <code>name</code> are: <b>record</b>.
     **/
    public java.lang.Object getElement(java.lang.String name, int index)
    {
        name = getSubstitute(name);
        if (name.equals("Record"))
        {
            if (this.record == null)
                throw new java.lang.ArrayIndexOutOfBoundsException();
            else
                return this.record[index];
        }
        else
            return super.getElement(name, index);
    }

    /**
     * Returns the count of elements called <code>name</code>.<p>
     * The legal value(s) for <code>name</code> are defined in {@link #getElement}.
     **/
    public int getElementCount(java.lang.String name)
    {
        name = getSubstitute(name);
        if (name.equals("Record"))
            return this.record == null ? 0 : this.record.length;
        else
            return super.getElementCount(name);
    }

    /**
     * Returns the element called <code>name</code> at <code>index</code>.<p>
     * The legal value(s) for <code>name</code> are defined in {@link #getElement}.
     **/
    public int getElementIndex(java.lang.String name, java.lang.Object element)
    {
        name = getSubstitute(name);
        if (name.equals("Record"))
            return getRecordIndex((biz.c24.io.csv.Record) element);
        else
            return super.getElementIndex(name, element);
    }

    /**
     * Gets the value of Record (0..*).
     * @return The value.
     **/
    public biz.c24.io.csv.Record[] getRecord()
    {
        if (this.record == null)
            return new biz.c24.io.csv.Record[]{};
        else
            return this.record;
    }

    /**
     * Gets the index of <code>value</code> (0..*).
     * @param value The Record to get the index of.
     * @return The index.
     **/
    public int getRecordIndex(biz.c24.io.csv.Record value)
    {
        if (this.record == null)
            return -1;
        for (int i=0; i<this.record.length; i++)
            if (this.record[i] == value)
                return i;
        return -1;
    }

    public int hashCode()
    {
        return super.hashCode();
    }

    /**
     * Removes the element called <code>name</code> at <code>index</code>.<p>
     * The legal value(s) for <code>name</code> are defined in {@link #getElement}.
     **/
    public void removeElement(java.lang.String name, int index)
    {
        name = unmakeSubstitution(name, index);
        if (name.equals("Record"))
            removeRecord(index);
        else
            super.removeElement(name, index);
    }

    /**
     * Removes a Record (0..*).
     * @param index The index of the Record to get.
     **/
    public void removeRecord(int index)
    {
        if (this.record == null)
            throw new java.lang.ArrayIndexOutOfBoundsException();
        biz.c24.io.csv.Record[] temp = this.record;
        this.record = new biz.c24.io.csv.Record[temp.length-1];
        java.lang.System.arraycopy(temp, 0, this.record, 0, index);
        java.lang.System.arraycopy(temp, index+1, this.record, index, temp.length-index-1);
        ((biz.c24.io.api.data.ComplexDataObject) temp[index]).setParent(null);
        if (this.record.length == 0)
            this.record = null;
    }

    /**
     * Sets <code>value</code> as an element called <code>name</code> at <code>index</code>.<p>
     * The legal value(s) for <code>name</code> are defined in {@link #getElement}.
     **/
    public void setElement(java.lang.String name, int index, java.lang.Object value)
    {
        name = makeSubstitution(name, index);
        if (name.equals("Record"))
        {
            if (this.record == null)
                throw new java.lang.ArrayIndexOutOfBoundsException();
            else
                this.record[index] = (biz.c24.io.csv.Record) value;
        }
        else
            super.setElement(name, index, value);
    }

    /**
     * Sets the value of Record (0..*).
     * @param value The new value.
     **/
    public void setRecord(biz.c24.io.csv.Record[] value)
    {
        this.record = (biz.c24.io.csv.Record[]) biz.c24.io.api.Utils.clearNulls(value);
        for (int i=0; this.record != null && i<this.record.length; i++)
            ((biz.c24.io.api.data.ComplexDataObject) this.record[i]).setParent(this);
    }

    private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException
    {
        out.writeObject(this.record);
    }

    private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException
    {
        this.record = (biz.c24.io.csv.Record[]) in.readObject();
    }

}
