package org.trimet.db;
// Generated Dec 30, 2005 12:44:58 PM by Hibernate Tools 3.1.0 beta1JBIDERC2

import java.util.Date;


/**
 * TripId generated by hbm2java
 */

public class TripId  implements java.io.Serializable {


    // Fields    

     private short routeNumber;
     private boolean direction;
     private String serviceKey;
     private short tripNumber;
     private Date tripBeginDate;


    // Constructors

    /** default constructor */
    public TripId() {
    }

    
    /** full constructor */
    public TripId(short routeNumber, boolean direction, String serviceKey, short tripNumber, Date tripBeginDate) {
        this.routeNumber = routeNumber;
        this.direction = direction;
        this.serviceKey = serviceKey;
        this.tripNumber = tripNumber;
        this.tripBeginDate = tripBeginDate;
    }
    

   
    // Property accessors

    public short getRouteNumber() {
        return this.routeNumber;
    }
    
    public void setRouteNumber(short routeNumber) {
        this.routeNumber = routeNumber;
    }

    public boolean isDirection() {
        return this.direction;
    }
    
    public void setDirection(boolean direction) {
        this.direction = direction;
    }

    public String getServiceKey() {
        return this.serviceKey;
    }
    
    public void setServiceKey(String serviceKey) {
        this.serviceKey = serviceKey;
    }

    public short getTripNumber() {
        return this.tripNumber;
    }
    
    public void setTripNumber(short tripNumber) {
        this.tripNumber = tripNumber;
    }

    public Date getTripBeginDate() {
        return this.tripBeginDate;
    }
    
    public void setTripBeginDate(Date tripBeginDate) {
        this.tripBeginDate = tripBeginDate;
    }
   



   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TripId) ) return false;
		 TripId castOther = ( TripId ) other; 
         
		 return (this.getRouteNumber()==castOther.getRouteNumber())
 && (this.isDirection()==castOther.isDirection())
 && ( (this.getServiceKey()==castOther.getServiceKey()) || ( this.getServiceKey()!=null && castOther.getServiceKey()!=null && this.getServiceKey().equals(castOther.getServiceKey()) ) )
 && (this.getTripNumber()==castOther.getTripNumber())
 && ( (this.getTripBeginDate()==castOther.getTripBeginDate()) || ( this.getTripBeginDate()!=null && castOther.getTripBeginDate()!=null && this.getTripBeginDate().equals(castOther.getTripBeginDate()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getRouteNumber();
         result = 37 * result + (int) this.isDirection();
         result = 37 * result + ( getServiceKey() == null ? 0 : this.getServiceKey().hashCode() );
         result = 37 * result + (int) this.getTripNumber();
         result = 37 * result + ( getTripBeginDate() == null ? 0 : this.getTripBeginDate().hashCode() );
         return result;
   }   





}
