package org.trimet.db;
// Generated Dec 30, 2005 12:44:57 PM by Hibernate Tools 3.1.0 beta1JBIDERC2

import java.util.Date;


/**
 * Trip generated by hbm2java
 */

public class Trip  implements java.io.Serializable {


    // Fields    

     private TripId id;
     private RouteDirection routeDirection;
     private Date tripEndDate;
     private short patternId;
     private Character tripType;
     private Character accessible;
     private Character variantServiceKey;
     private short train;
     private Character trainPiece;
     private Integer tripBeginTime;
     private Integer tripEndTime;
     private String tripOriginDescription;
     private String tripDestinationDescription;
     private Date arbiterTimestamp;
     private String replicationSite;


    // Constructors

    /** default constructor */
    public Trip() {
    }

	/** minimal constructor */
    public Trip(TripId id, RouteDirection routeDirection, Date tripEndDate, short patternId, Character tripType, Character accessible, Character variantServiceKey, short train, Character trainPiece, Integer tripBeginTime, Integer tripEndTime, String tripOriginDescription, String tripDestinationDescription) {
        this.id = id;
        this.routeDirection = routeDirection;
        this.tripEndDate = tripEndDate;
        this.patternId = patternId;
        this.tripType = tripType;
        this.accessible = accessible;
        this.variantServiceKey = variantServiceKey;
        this.train = train;
        this.trainPiece = trainPiece;
        this.tripBeginTime = tripBeginTime;
        this.tripEndTime = tripEndTime;
        this.tripOriginDescription = tripOriginDescription;
        this.tripDestinationDescription = tripDestinationDescription;
    }
    
    /** full constructor */
    public Trip(TripId id, RouteDirection routeDirection, Date tripEndDate, short patternId, Character tripType, Character accessible, Character variantServiceKey, short train, Character trainPiece, Integer tripBeginTime, Integer tripEndTime, String tripOriginDescription, String tripDestinationDescription, Date arbiterTimestamp, String replicationSite) {
        this.id = id;
        this.routeDirection = routeDirection;
        this.tripEndDate = tripEndDate;
        this.patternId = patternId;
        this.tripType = tripType;
        this.accessible = accessible;
        this.variantServiceKey = variantServiceKey;
        this.train = train;
        this.trainPiece = trainPiece;
        this.tripBeginTime = tripBeginTime;
        this.tripEndTime = tripEndTime;
        this.tripOriginDescription = tripOriginDescription;
        this.tripDestinationDescription = tripDestinationDescription;
        this.arbiterTimestamp = arbiterTimestamp;
        this.replicationSite = replicationSite;
    }
    

   
    // Property accessors

    public TripId getId() {
        return this.id;
    }
    
    public void setId(TripId id) {
        this.id = id;
    }

    public RouteDirection getRouteDirection() {
        return this.routeDirection;
    }
    
    public void setRouteDirection(RouteDirection routeDirection) {
        this.routeDirection = routeDirection;
    }

    public Date getTripEndDate() {
        return this.tripEndDate;
    }
    
    public void setTripEndDate(Date tripEndDate) {
        this.tripEndDate = tripEndDate;
    }

    public short getPatternId() {
        return this.patternId;
    }
    
    public void setPatternId(short patternId) {
        this.patternId = patternId;
    }

    public Character getTripType() {
        return this.tripType;
    }
    
    public void setTripType(Character tripType) {
        this.tripType = tripType;
    }

    public Character getAccessible() {
        return this.accessible;
    }
    
    public void setAccessible(Character accessible) {
        this.accessible = accessible;
    }

    public Character getVariantServiceKey() {
        return this.variantServiceKey;
    }
    
    public void setVariantServiceKey(Character variantServiceKey) {
        this.variantServiceKey = variantServiceKey;
    }

    public short getTrain() {
        return this.train;
    }
    
    public void setTrain(short train) {
        this.train = train;
    }

    public Character getTrainPiece() {
        return this.trainPiece;
    }
    
    public void setTrainPiece(Character trainPiece) {
        this.trainPiece = trainPiece;
    }

    public Integer getTripBeginTime() {
        return this.tripBeginTime;
    }
    
    public void setTripBeginTime(Integer tripBeginTime) {
        this.tripBeginTime = tripBeginTime;
    }

    public Integer getTripEndTime() {
        return this.tripEndTime;
    }
    
    public void setTripEndTime(Integer tripEndTime) {
        this.tripEndTime = tripEndTime;
    }

    public String getTripOriginDescription() {
        return this.tripOriginDescription;
    }
    
    public void setTripOriginDescription(String tripOriginDescription) {
        this.tripOriginDescription = tripOriginDescription;
    }

    public String getTripDestinationDescription() {
        return this.tripDestinationDescription;
    }
    
    public void setTripDestinationDescription(String tripDestinationDescription) {
        this.tripDestinationDescription = tripDestinationDescription;
    }

    public Date getArbiterTimestamp() {
        return this.arbiterTimestamp;
    }
    
    public void setArbiterTimestamp(Date arbiterTimestamp) {
        this.arbiterTimestamp = arbiterTimestamp;
    }

    public String getReplicationSite() {
        return this.replicationSite;
    }
    
    public void setReplicationSite(String replicationSite) {
        this.replicationSite = replicationSite;
    }
   








}
