package com.llic.domain;


/**
 * com.llic.domain.EntityRoleType generated by hbm2java
 */
public class EntityRoleTypeBase  implements LaserDomain,java.io.Serializable {

    // Fields    

    private java.lang.Long id;
    private java.lang.String code;
    private java.lang.String description;
    private java.util.Map subTypeCodeMap;
    private java.util.Map subTypeIdMap;


    // Constructors

    /** default constructor */
    public EntityRoleTypeBase() {
    }
    
    /** constructor with id */
    public EntityRoleTypeBase(java.lang.Long id) {
        this.id = id;
    }
    
    

    // Property accessors
    /**
     */
   public java.lang.Long getId () {
        return this.id;
    }
    
   public void setId (java.lang.Long id) {
        this.id = id;
    }
    /**
     */
   public java.lang.String getCode () {
        return this.code;
    }
    
   public void setCode (java.lang.String code) {
        this.code = code;
    }
    /**
     */
   public java.lang.String getDescription () {
        return this.description;
    }
    
   public void setDescription (java.lang.String description) {
        this.description = description;
    }
    /**
     */
   public java.util.Map getSubTypeCodeMap () {
        return this.subTypeCodeMap;
    }
    
   public void setSubTypeCodeMap (java.util.Map subTypeCodeMap) {
        this.subTypeCodeMap = subTypeCodeMap;
    }
    /**
     */
   public java.util.Map getSubTypeIdMap () {
        return this.subTypeIdMap;
    }
    
   public void setSubTypeIdMap (java.util.Map subTypeIdMap) {
        this.subTypeIdMap = subTypeIdMap;
    }

   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof EntityRoleTypeBase) ) return false;
		 EntityRoleTypeBase castOther = ( EntityRoleTypeBase ) other; 
         
		 return (this.getId()==castOther.getId()) || (this.getId()==null ? false : (castOther.getId()==null ? false : this.getId().equals(castOther.getId())));
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getId().hashCode();
         ;
         ;
         ;
         ;
         return result;
   }   



}